ice40/tiles/plb/pb_type.xml

Trivial fix - interconnect names must not contain spaces (name="i to o"), else they are interpreted as multiple nets (a compound name containing "i", a net named "to", and a net named "o").

Use interconnect names without spaces

---

ice40/arch/ice40-virt/arch.xml

This allows the FF test for the iCE40 to get to the placement stage, fixing the assert failure, but routing still fails with the below message:
```
Warning 1078: Empty heap occurred in get_heap_head.
Warning 1079: Some blocks are impossible to connect in this architecture.
Cannot route from PAD.inpad[0] (rr_node: 1 type: SOURCE ptc: 1 xlow: 1 ylow: 2) to PLB.o_neigh_op_rgt[2] (rr_node: 49 type: SINK ptc: 19 xlow: 2 ylow: 2) to -- no possible path
Failed to route connection from 'di' to 'D1' for net 'di'
Routing failed.
Attempting to route at 1832 channels (binary search bounds: [916, -1])
Routing took 13.52 seconds
Error 1: 
Type: Routing
File: /home/david/vtr-verilog-to-routing/vpr/src/base/place_and_route.cpp
Line: 165
Message: This circuit requires a channel width above 1000, probably …
```

Fix typo: replace o_neigh_xxx with o_neigh_op_xxx in ice40

---

Makefile

make: `dist-clean` depends on `clean` now.

---

artix7/blocks/clbll_l-int_l/pb_type.xml
artix7/blocks/int_r-clbll_r/pb_type.xml
artix7/devices/xc7a50t-roi-virt/dummy/dummy.sh
artix7/devices/xc7a50t-virt/arch.xml.unused
artix7/dummy.xml
artix7/empty.xml
ice40/cells/plb/plb.pb_type.xml
ice40/devices/ice4/arch.xml
ice40/tiles/pio-lr/pio-lr.pb_type.xml
ice40/tiles/pio-tb/pio-tb.pb_type.xml
ice40/tiles/plb/plb.pb_type.xml
ice40/tiles/ramb/ramb.pb_type.xml
ice40/tiles/ramt/ramt.pb_type.xml
testarch/tile/ff-large/ff-large.pb_type.xml
testarch/tile/ff1/ff1.pb_type.xml
testarch/tile/lutff/lutff.pb_type.xml
testarch/tile/lutff3/lutff3.pb_type.xml
vpr/pad/pad.pb_type.xml

This is required as a result of the breaking change in verilog-to-routing/vtr-verilog-to-routing#308 (don't merge before the VTR PR is merged).

Upgrade VPR arch: remove default_ prefix from <fc> attributes

---

testarch/devices/lutff-bidir-s4-g/arch.xml
testarch/devices/routing/bidir-s4-g.xml
testarch/devices/routing/bidir-s4.xml
testarch/devices/routing/device.xml
testarch/devices/routing/unidir-s4.xml

Longlines connect to every tile in the device. See;
https://docs.verilogtorouting.org/en/latest/arch/reference/#tag-wire-segments-segment

testarch: Adding a testarch with a longline in it.

---

make/inc/func.mk

Before you have the environment setup, `import icebox` will fail causing
no outputs to be found which prevents you from getting the environment
set up.

make: Don't error on no outputs.

---

common/xml/xmlsort.xsl
ice40/devices/top-routing-virt/tiles/dsp/dsp.pb_type.xml
ice40/devices/top-routing-virt/tiles/pio/pio.pb_type.xml
ice40/devices/top-routing-virt/tiles/plb/plb.pb_type.xml
ice40/devices/top-routing-virt/tiles/ram/ram.pb_type.xml
ice40/primitives/sb_ff/dff.pb_type.xml
ice40/primitives/sb_ff/dffe.pb_type.xml
ice40/primitives/sb_ff/dffes.pb_type.xml
ice40/primitives/sb_ff/dffs.pb_type.xml
ice40/primitives/sb_ff/sb_ff.pb_type.xml
ice40/primitives/sb_io/sb_io.pb_type.xml
ice40/primitives/sb_lut/sb_lut.pb_type.xml
ice40/primitives/sb_ram/sb_ram.pb_type.xml
utils/vlog/vlog_to_pbtype.py

* Remove the equivalent property.
* Use an alternative XML format which allows `<xi:include` to work.
The most important change is the following;
---
> Support a format for pb_type which doesn't require repeating the name
> many times. Use the xmlsort style sheet to generate the old XML version.
> 
> The changes are;
>  * Remove the requirement to give an interconnect a name.
>  * Moving from attributes for input/output to "port" tags.
>  * Decompose the old `PB_TYPE.PORT[BIT]` into attributes on "port" tag.
>  * "Port" tags have a `from` attribute. If left blank it defaults to the
>    current pb_type.
> 
> Before;
> ```xml
> <direct input="XXXX.CLOCK_ENABLE" output="in_cen.EN" name="XXXX">
> ```
> 
> After;
> ```xml
> <direct>
>   <port name="CLOCK_ENABLE" type="input"/>
>   <port …
```

Rework the XML format for pb_type to better allow composition

---

ice40/make/tests.mk
ice40/tests/blink/example_tb.v
ice40/tests/blink/hx8k-b-evn.pcf
ice40/tests/iceram/Makefile
ice40/tests/iceram/hx8k-b-evn.pcf

Added BOARD=hx8k-b-evn and PCF files for blink and iceRAM.
* fixed iceRAM test
* fixed testbinch for blink (example_bit.v order not known)

ice40/tests: Adding hx8k-b-evn support for blink and iceram

---

ice40/devices/top-routing-virt/tiles/dsp/dsp.pb_type.xml
ice40/devices/top-routing-virt/tiles/pio/pio.pb_type.xml
ice40/devices/top-routing-virt/tiles/plb/plb.pb_type.xml
ice40/devices/top-routing-virt/tiles/ram/ram.pb_type.xml

These were missed in #183.
Fixes the following from @elmsfu;
```
Error 1: ice40/build/ice40-top-routing-virt-up5k/arch.xml:1136 Expected 'name' attribute on node 'direct'
offending line 1136:
<direct input="BLK_TL-PLB.lutff_0/in" output="BLK_IG-PLB.I0"/>
```

ice40: Fixed <direct connections.

---

ecp5/primitives/slice/CCU2C/CCU2C.sim.v
ecp5/primitives/slice/DPR16X4C/DPR16X4C.sim.v
ecp5/primitives/slice/LUT2/LUT2.sim.v
ecp5/primitives/slice/LUT4/LUT4.sim.v
ecp5/primitives/slice/TRELLIS_DPR16X4/TRELLIS_DPR16X4.sim.v
ecp5/primitives/slice/TRELLIS_FF/TRELLIS_FF.sim.v
ecp5/primitives/slice/TRELLIS_RAM16X2/TRELLIS_RAM16X2.sim.v

- Change how LUTs are implemented so that "don't care" inputs at 'X' don't force the output to 'X' 
- Fix missing "cemux" conditional in TRELLIS_FF
- Other small tweaks

ecp5: Simulation model fixes

---

ice40/cells/lutff/lutff.pb_type.xml
ice40/cells/plb/plb.pb_type.xml
ice40/make/tests.mk
ice40/primitives/sb_ff/README.md
ice40/primitives/sb_ff/sb_ff.pb_type.xml
ice40/primitives/sb_lut/sb_lut.pb_type.xml
ice40/tests/ffpack/example_tb.v

* Add a README file with description of the flip flop types.
* Add `hlc_property` values for the different flip flop configurations.
* Support proper packing of flip flop types (IE don't pack `cen` / non-`cen` and `sr` / non-`sr` flip flops together).
* Improve testbench slightly.

ice40: Fixing the flip flop primitive

---

ice40/boards.cmake
ice40/tests/blink/CMakeLists.txt
make/devices.cmake
tests/CMakeLists.txt

TinyFPGA BX and TinyFPGA B2 support are still missing, will be added in a follow up CL.  They require adding pip install hooks through conda.

Add support for designs that target multiple boards.

---

utils/lib/rr_graph/points.py
utils/lib/rr_graph/tracks.py

The previous point algorithm was more complicated than required, and didn't handle all cases.  The new algorithm is more robust, though it may be less optimum.
A follow on will add a function that converts x-lines and y-lines and points and outputs VPR tracks, along with connections.
In particular, the last doctest in the new function caused the previous algorithm to return a disjoint set of lines.

Implement more robust points to tracks algorithm.

---

artix7/primitives/common_slice/common_slice.pb_type.xml

This PR partially fixes #311. The build passes up to `top.frames` generation and it fails on patching the bistream with:
```
[100%] Generating counter/artix7-xc7a50t-roi-virt-xc7a50t-test/top.bit
frame address 0x2049e because it was not found in frames.
```
The changes in this PR mostly fix the `pb_types` definitions so they match latest prjxray-db

Basys3 counter demo fix

---

ice40/CMakeLists.txt
make/devices.cmake
xc7/make/arch_define.cmake

VPR_ARCH_ARGS was being ignored in cmake define_arch()
ice40 tests should complete now.
Also added ability to specify conda package versions and builds. This was helpful in bisecting the failure and will be good for any release or milestone.

Fix VPR_ARCH_ARGS

---

xc7/make/arch_define.cmake

This includes required_features (like the clock tree) that was getting zero'd in some circumstances.

Use new --roi flag in fasm2frames

---

library/uart/uart_tx.v
xc7/techmap/cells_map.v
xc7/tests/bram_test/error_output_logic.v
xc7/tests/bram_test/read_uart.py
xc7/utils/prjxray_routing_import.py

- Correct WE signals for TDP BRAM.
- Add loop count to result report
- Explicitly initialize UART Tx output state.
BRAM INIT contents is still not handled correctly.

Fix BRAM test.

---

xc7/make/arch_define.cmake

https://github.com/SymbiFlow/vtr-verilog-to-routing/pull/9 should be merged before this PR

arch_define.cmake: added round_robin option to arch definition

---

xc7/utils/prjxray_tile_import.py

It was previously ignored does not match features in db
This should merge once genfasm conda package has https://github.com/SymbiFlow/vtr-verilog-to-routing/pull/12

Remove tile level fasm_prefix

---

make/devices.cmake

Looks like this was removed at some point. Adding back for quicker checking of techmapping etc.

add back _eblif targets

---

ice40/yosys/synth.tcl

When the fix for libblifparse is merged and propagated to VPR this can be reverted
Signed-off-by: Elms <elms@freshred.net>

ice40: Temp fix for build by running `abc` separately without -dress

---

CMakeLists.txt
testarch/CMakeLists.txt

Fixes #436
- Updates to VPR that includes HLC binary
- Updates to VPR that disables randomly failing placer cost check (see https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/485).  This is a workaround.

Fix Travis CI.

---

make/devices.cmake

After the `vtr` rebase with mainline `debug_clustering` option has been changed to `pack_verbosity`

devices.cmake: changed VPR pack debug option

---

utils/lib/connection_database.py
utils/lib/rr_graph/graph2.py
utils/lib/rr_graph_xml/graph2.py
xc7/make/device_define.cmake
xc7/make/project_xray.cmake
xc7/utils/prjxray_arch_import.py
xc7/utils/prjxray_assign_tile_pin_direction.py
xc7/utils/prjxray_create_edges.py
xc7/utils/prjxray_create_synth_tiles.py
xc7/utils/prjxray_form_channels.py
xc7/utils/prjxray_routing_import.py

This converts the xc7 routing graph import from using channels.json to channels.db, a sqlite3 database.  This was done for several reasons:
- Certain operations (e.g. pruning dead nodes) was fairly difficult in the previous data structure and layout.
- Memory usage was very high as a side affect of keeping all data in memory
- Parse times of channels.json (~800 MB) was high.
- It was hard to see what was taking time, because database-like operations were in the code.  Now data lookup is explicit and can be optimized via SQL indicies or denormalized tables if shown to be required.
In addition, by moving to a database to keep relations between tiles, wires, nodes (prjxray node), graph_node (VTR rr_node), and graph_edges (VTR rr_edge) to the database, it should be easier to do optimizations …

Initial SQLite3 XC7 routing graph implementation.

---

make/devices.cmake
xc7/yosys/synth.tcl

Added generation of Yosys log in the build system. Added printing of primitive usage statistics to Yosys script for XC7 (`xc7/yosys/synth.tcl`). Very useful for debugging.

Yosys log and statistics

---

xc7/make/project_xray.cmake
xc7/tests/chain_packing/counter.v
xc7/utils/prjxray_assign_tile_pin_direction.py
xc7/utils/prjxray_create_edges.py
xc7/utils/prjxray_db_cache.py
xc7/utils/prjxray_form_channels.py
xc7/utils/prjxray_routing_import.py

While working with arch defs I've noticed that recent changes regarding SQLite introduction dramatically slowed down process of prjxray database import. I've narrowed it down to problem with frequent writing of small chunks of data to the SQL database on disk. So I've created a wrapper which creates a temporary copy of the database in memory and all subsequent operations are performed on it.
I also added missing Python dependencies to the CMake build scripts.

SQLite database cache

---

utils/lib/connection_database.py

This PR is to fix a few bugs in `connection_database.py`:
- with `c.execute()` the following warning was produced (which ended up in a fatal error) `sqlite3.Warning: You can only execute one statement at a time`

connection_database: fixing bug in table_create

---

xc7/utils/prjxray_routing_import.py

Opening database in read-write mode causes build system to
rebuild *rr_graph.real.xml everytime when compiling project.
It caused by the fact .xml file is generated before channels.db is
flushed.
Signed-off-by: Lukasz Dalek <ldalek@antmicro.com>

xc7: fix channel.db dependencies

---

xc7/make/device_define.cmake

This PR clears variable DEVICE_RR_PATCH_DEPS before
appending new dependencies to it.
Signed-off-by: Lukasz Dalek <ldalek@antmicro.com>

xc7: Fix dependencies for different boards

---

xc7/tests/bram_init_test/top.v
xc7/tests/bram_sdp_init_test/top.v
xc7/tests/bram_sdp_test/top.v
xc7/tests/bram_test/top.v
xc7/tests/common/basys3.pcf
xc7/tests/dram_test/top.v

This is required for clean fasm2bel usage.

Modify BRAM and DRAM tests to use all top level pins.

---

ice40/yosys/synth.tcl
make/devices.cmake
testarch/yosys/synth.tcl
xc7/yosys/synth.tcl

This is required to enable 7-series constant generator support using the
write_blif -true/-false arguments.

Move output writing into Yosys tcl script.

---

utils/lib/connection_database.py
xc7/make/arch_define.cmake
xc7/primitives/common_slice/common_slice.pb_type.xml
xc7/primitives/ff/ff.model.xml
xc7/primitives/ff/ff.pb_type.xml
xc7/primitives/slicel/ntemplate.slicelN.pb_type.xml
xc7/primitives/slicem/Ndram/d_dram.pb_type.xml
xc7/primitives/slicem/Ndram/ntemplate.N_dram.model.xml
xc7/primitives/slicem/slicem.pb_type.xml

- Output CEUSEDMUX and SRUSEDMUX only when required (e.g. CE or SR
signal is used).
- Only output FFSYNC if FDSE or FDRE is used.
- Only output DLUT.RAM if a DRAM is actually used.
- Change order of DRAM packing to pack into DLUT before CLUT, etc.

WIP: Fixes for based FASM output found via fasm2bels.

---

xc7/utils/prjxray_db_cache.py

If the database cache __exit__ method is called when a transaction
is in progress, it will never proceed.  Handle the exception case by
rolling back, and generate an assertion error in the nominal path.
Fixes #482.

Fix database cache for in progress transactions.

---

make/devices.cmake
xc7/fasm2bels/__main__.py
xc7/fasm2bels/bram_models.py
xc7/fasm2bels/clb_models.py
xc7/fasm2bels/clk_models.py
xc7/fasm2bels/connection_db_utils.py
xc7/fasm2bels/fasm2bels.py
xc7/fasm2bels/iob_models.py
xc7/fasm2bels/make_routes.py
xc7/fasm2bels/verilog_modeling.py
xc7/make/arch_define.cmake
xc7/make/device_define.cmake

This correctly works on designs with the following restrictions:
- IO's must not use IDDR, ODDR, ISERDES, or OSERDES
- IO's must be single ended
- Only sites from IOB33, IOI33, CLBxx_x, BRAM_x, BUFGCTRL and BUFHCE tiles are supported.
- RAMB36 is not supported
- RAMB18 designs will have different routing for constants connected to the WEBWE and WEA ports.  This results in a significant different in routing pips, but should result in functionally identical output.
- Constant routes are not explicitly specified, resulting in a small feature variations, but no functional differences.
- VPR designs should use all top-level ports, or significant differences will result.

fasm2bels implementation.

---

CMakeLists.txt
testarch/devices/CMakeLists.txt
testarch/utils/testarch_graph.py
utils/lib/rr_graph/graph2.py
utils/lib/rr_graph_xml/graph2.py
xc7/CMakeLists.txt

Removes use of graph (per #339) and lays groundwork for constant routing experiment.
This also exposed some bugs in some paths of the graph2 library, which are fixed.
Also fixes #486

Convert testarch to graph2 library.

---

CMakeLists.txt
make/env.cmake

Following the same philosophy for conda packages, this PR locks the miniconda version to a particular version, rather than grabbing the latest version.

Lock miniconda version.

---

CMakeLists.txt
make/devices.cmake
make/env.cmake
xc7/make/project_xray.cmake

- Add lock files for conda and pip installations to prevent those tools
from being invoked in parallel.
- Change some file dependencies to target dependencies, which is
important when multiple process builds occur.
- Remove eblif and bit files from ALL, instead only having the conda environment on all.
Fixes #448, fixes #337

Fix multi-process bugs in CMake build system.

---

make/devices.cmake
tests/0-const/CMakeLists.txt
tests/6-led/CMakeLists.txt
tests/6-rot/CMakeLists.txt
tests/CMakeLists.txt
xc7/yosys/synth.tcl

Because of how the ROI is defined, the global constant network cannot be
connected directly to the OPADs of the ROI.  Selectively disable the global
constant network on designs that tie OPADs directly to VCC or GND.
Fixes #544

[XC7] Make use of global constant network optional.

---

CMakeLists.txt
make/devices.cmake

@mithro and @elmsfu Does this address https://github.com/SymbiFlow/symbiflow-arch-defs/issues/539 ?
This doesn't tie them into the true all target, but I don't think we want to.

Adds route grouping targets and all targets for major variants.

---

CMakeLists.txt
tests/9-scalable_proc/CMakeLists.txt
tests/9-scalable_proc/basys3_top.v
tests/9-soc/picosoc/CMakeLists.txt
xc7/tests/dram/CMakeLists.txt
xc7/tests/simple_ff/simple_ff.v

The intention is to get kokoro green with the targets that are working.  3 issues have been filed to track the targets disabled in this PR.
Issues filed #548, #549, #550

Disable targets that are broken to get initial green CI.

---

ice40/CMakeLists.txt

Increase wire length threshold to allow picosoc routing to proceed.

Wire length metric can sometimes incorrect stop routing.

---

utils/lib/parse_pcf.py
xc7/fasm2bels/fasm2bels.py
xc7/fasm2bels/verilog_modeling.py
xc7/make/arch_define.cmake
xc7/utils/prjxray_create_ioplace.py

This is useful for binding to test benches and equivilence miter
circuits.

Add support for naming top-level port names based on pcf file.

---

.gitmodules
make/devices.cmake
xc7/tests/ff_sr_ce/CMakeLists.txt
xc7/tests/ff_sr_ce/create_sby.py
xc7/tests/ff_sr_ce/ff_ce_sr.v
xc7/tests/ff_sr_ce/ff_type.v
xc7/tests/ff_sr_ce/generate.py

This PR adds SymbiYosys to third_party and uses it to prove equivalence on the FF CE/SR tests.  This PR also expands the FF CE/SR test to the other 3 FD types (FDSE, FDPE, FDCE).
This PR is dependent on https://github.com/SymbiFlow/symbiflow-arch-defs/pull/570 (which is blocked by https://github.com/SymbiFlow/prjxray-db/pull/7).
This takes a first attempt at #572 by using submodules.  This is fine for the "PASS" case, but in the failure case, another SMT2 solver needs to be installed.  However for the purposes of getting an equivalence testing working on the FF CE/SR test, this does work.

Use SymbiYosys to prove FF CE/SR tests

---

tests/9-scalable_proc/CMakeLists.txt
tests/9-scalable_proc/basys3.pcf
tests/9-scalable_proc/basys3_top.v
tests/9-scalable_proc/utils/receiver.py
xc7/make/arch_define.cmake

- Remove clock divider from scalable tests.
- Use all IO pins in ROI.
- Re-enable round robin packing.

Make scalable tests debuggable with fasm2v

---

xc7/primitives/common_slice/common_slice.model.xml
xc7/primitives/common_slice/common_slice.pb_type.xml
xc7/primitives/ff/ff.pb_type.xml
xc7/techmap/cells_map.v
xc7/techmap/cells_sim.v

This has been tested with https://github.com/SymbiFlow/symbiflow-arch-defs/pull/575

Add explicit CEUSEDMUX and SRUSEDMUX support.

---

make/gen.cmake
utils/n.py

V2X and N_TEMPLATE now can handle dependency on a generated XML or Verilog file. The list of the dependencies can be passed via GENERATEDXMLDEPS and GENERATEDVERILOGDEPS for both n_template and v2x functions.
This may fix #262

gen.cmake: handle generated verilog and xml deps

---

utils/lib/connection_database.sql
xc7/utils/prjxray_assign_tile_pin_direction.py
xc7/utils/prjxray_create_edges.py
xc7/utils/prjxray_form_channels.py
xc7/utils/prjxray_routing_import.py

This PR adds additional columns to the `pip_in_tile` table namely: `can_invert`, `is_directional` and `is_pseudo`. All pseudo pips are now imported from the prjxray database instead of being rejected. All SQL queries regarding the `pip_in_tile` table table were modified to reject pseudo and bidirectional pips.

Import of all pips (bidirectional and pseudo) to channels.db

---

Makefile

Small fix to forwarding from the top level makefile to the targets in `build/Makefile`.
* Don't always call `make env` unless `build/Makefile` doesn't exist.
* Actually seems to work with tab complete!?

infra: Fixing the Makefile forwarding.

---

utils/vlog/tests/dsp_out_registered/golden.pb_type.xml
utils/vlog/vlog_to_pbtype.py

Before this commit direct connections were in the following format:
```
<direct>
<port name="out[0]" type="input"/>
<port from="dsp_in_registered" name="out[0]" type="output"/>
</direct>
```
Direct connections's correct format is the following:
```
<direct input="<input>" name="<name>" output="<output>"/>
```

v2x: direct connections now are in the old format

---

utils/vlog/tests/v2x_tests.cmake

This PR has two different changes:
- clean the v2x_cmake file by adding local variables for the test names and types (this increases readability).
- Added custom command to automatically update the `golden.<pb_type/model>.xml` in the relative source directory. (The update golden target should be used only if the developer is sure that the output of v2x is correct)

v2x: adding update_golden command in v2x cmake

---

utils/vlog/tests/dsp_out_registered/golden.pb_type.xml
utils/vlog/vlog_to_pbtype.py

This reverts commit b1fca60f8c5e47fd54aeeb683f026109a72d9570.
This PR is WIP as by looking at the description of the **new** format in https://github.com/SymbiFlow/symbiflow-arch-defs/issues/642, `vlog_to_pbtype.py` incorrectly handles the direct connections. In particular all cell related signals are always treated as outputs.
I will remove WIP as soon as the tool creates direct connections consistent with https://github.com/SymbiFlow/symbiflow-arch-defs/issues/642.

Revert "v2x: direct connections now are in the old format"

---

xc7/techmap/cells_map.v

Corrected passing of the `IS_WCLK_INVERTED` parameter for `RAM128X1D` and `RAM32X1D` primitives
Signed-off-by: Maciej Kurc <mkurc@antmicro.com>

Fixed the IS_WCLK_INVERTED parameter in DRAM techmaps.

---

xc7/tests/CMakeLists.txt
xc7/tests/common/CMakeLists.txt
xc7/tests/common/ram_shifter.v
xc7/tests/dram_shifter/CMakeLists.txt
xc7/tests/dram_shifter/dram_shifter_32x1d.v
xc7/tests/dram_shifter/dram_shifter_32x1s.v
xc7/tests/dram_shifter/dram_shifter_64x1d.v
xc7/tests/dram_shifter/dram_shifter_64x1s.v

This adds a test that runs input from switches and output to LEDs on the BASYS3 through a single bit output RAM.
I'm adding one target in this PR to get feedback, and then I'll duplicate it across all memory types.

Add the RAM_SHIFTER module to make it easy to build simple RAM tests

---

CMakeLists.txt
xc7/make/arch_define.cmake

This PR adds the `--disable_check_route` option after https://github.com/SymbiFlow/vtr-verilog-to-routing/pull/48

devices.cmake: added disable check route option

---

xc7/primitives/bram/bram.pb_type.xml
xc7/tests/bram_shifter/bram_shifter.v

Instead of inferring block RAM. In preparation for RAM36E1 tests.

use RAMB18E1 primitive in bram_shifter

---

.github/travis/common.sh
.github/travis/script.sh

The `travis_xxxx` are probably not defined locally, so if they are not - define them. Plus tell user the make command to replicate output.

travis: Enable running scripts locally.

---

utils/lib/rr_graph_xml/graph2.py

This should fix master on CI, currently xc7 is broken at HEAD on master.

Enable Cinternal output.

---

common/cmake/devices.cmake
xc7/tests/common/CMakeLists.txt
xc7/tests/common/basys3.sdc
xc7/tests/dram_test/CMakeLists.txt

This enables constraints to be defined for VPR timing.

Add SDC support to ADD_FPGA_TARGET.

---

xc7/tests/counter/CMakeLists.txt
xc7/tests/counter/counter_basys3.v

This enables timing analysis comparisons between the two designs.

Make xc7 counter test for basys3 fasm2v compatible.

---

xc7/fasm2bels/net_map.py
xc7/fasm2bels/tests/test_verilog_modeling.py
xc7/fasm2bels/verilog_modeling.py

Prior to this PR, wires were always named programatically.
This PR uses net map to rename wires, and then propigates those names
back to the module instances.

Map wires to nets and flatten wires for easier tracing.

---

xc7/techmap/unmap.v
xc7/yosys/synth.tcl

This pre-symbiflow verilog can be used with Vivado synthesis if xc7/techmap/unmap.v is
applied.  This allows for post-Yosys timing comparisions between VPR and Vivado.

Output pre-symbiflow techmap'd Verilog.

---

utils/lib/connection_database.sql
xc7/utils/prjxray_create_edges.py
xc7/utils/prjxray_form_channels.py
xc7/utils/prjxray_routing_import.py

This is important for supporting long wires, as most bipips are
locationed on the long wires.

[xc7] Add support for bidirection pips.

---

utils/lib/mux.py

utils: Fix metadata attributes.

---

xc7/primitives/ff/ff.model.xml
xc7/primitives/ff/ff.pb_type.xml

This PR splits FFs definitions in the arch.xml so it corresponds with the actual FPGA arch. Also timings definitions are updated, but they do not have correct delay values.
This PR was originally a part of #738

xc7: dff: split dff into {FF|REG}_INIT and update timings

---

CMakeLists.txt
common/python_health_helper.sh
tox.ini

This adds a target that will display all linting errors. Once errors are addressed, this should be added to CI and the `--zero-exit` flag should be removed.

Add Python lint target

---

xc7/primitives/slicem/Ndram/dpram32.pb_type.xml

xc7: `DPRAM32` doesn't have `INIT_01` parameter.

---

xc7/primitives/ff/ff.model.xml
xc7/primitives/ff/ff.pb_type.xml

Makes it easier to look at.
* Cleanup some of the additions from https://github.com/SymbiFlow/symbiflow-arch-defs/pull/789
* Removed the unneeded values on `<direct><pack_pattern>` tags.

xc7: Fix formatting in ff XML files.

---

.github/kokoro/ice40.sh
.github/kokoro/testarch.sh
.github/kokoro/xc7.sh

To make it easier to see the errors when there is a failure on Kokoro while still running everything in parallel, we first;
1. Run tests in parallel and keep going on failure until all targets which can build have done so (`-k`).
2. Re-run in single threaded mode, stopping at the first error.

infra: Keep running and then rerun the errors.

---

xc7/techmap/cells_sim.v

This was causing simulations to output 1'bx for all CARRY4_VPR outputs.
This does not fix DRAM test error output problem, but it does fix autosim for cases where a sim model exists.

Removed blackbox attribute.

---

xc7/primitives/ff/ff.pb_type.xml

Alignment was broken in https://github.com/SymbiFlow/symbiflow-arch-defs/pull/738

xc7: Fix alignment in ff.pb_type.xml

---

CMakeLists.txt
common/cmake/devices.cmake
tests/7-carry_stress/generate_carry_test.py
xc7/tests/common/CMakeLists.txt
xc7/tests/common/error_output_logic.v
xc7/tests/common/error_output_logic_tb.v
xc7/tests/common/error_output_logic_unt.v

It is worth noting that none of the changes to error_output_logic.v changes synthesis, it just adds names to nets for ease of debugging.  The fix for the broken DRAM test was https://github.com/SymbiFlow/yosys/pull/29.
This PR will fail on CI until a yosys with https://github.com/SymbiFlow/yosys/pull/29 is included.

Add testbench for ERROR_OUTPUT_LOGIC.

---

.github/kokoro/ice40.sh
.github/kokoro/testarch.sh
.github/kokoro/tests.sh
.github/kokoro/xc7.sh

Makes it easier to know what target to run locally when something fails.

infra: Output which make targets are being built.

---

common/cmake/xml.cmake
common/xml/convert_and_merge_composable_fpga_architecture.sh
common/xml/convert_and_merge_composable_tests/composable-interconnect-existing-fasm-mux.golden.xml
common/xml/convert_and_merge_composable_tests/composable-interconnect-fasm-mux.golden.xml
common/xml/convert_and_merge_composable_tests/composable-interconnect-implicit-parent.golden.xml
common/xml/convert_and_merge_composable_tests/composable-interconnect-pack_patterns.golden.xml
common/xml/convert_and_merge_composable_tests/composable-pb_type.golden.xml
common/xml/convert_and_merge_composable_tests/full-test.golden.xml
common/xml/convert_and_merge_composable_tests/pack_pattern-copy-direct-ports.golden.xml
common/xml/convert_and_merge_composable_tests/preserve-interconnect.golden.xml
common/xml/sort-tags.xsl

```xml
<pb_type>
<clocks by name/>
<inputs by name/>
<outputs by name/>
<pb_type by name>
...
</pb_type>
<interconnect>
<direct|mux by output>
</interconnect>
</pb_type>
```

xml: Provide better sort order (sort by name) of XML output

---

utils/n.py
xc7/primitives/slicem/Ndram/ntemplate.N_dram.model.xml
xc7/primitives/slicem/Ndram/ntemplate.N_dram.pb_type.xml

Reduce duplication by using the
[`xc7/primitives/common_slice/Nlut/ntemplate.Nlut.pb_type.xml`](xc7/primitives/common_slice/Nlut/ntemplate.Nlut.pb_type.xml)
definition when
[`xc7/primitives/slicem/Ndram/ntemplate.Nd_ram.pb_type.xml`](xc7/primitives/slicem/Ndram/ntemplate.Nd_ram.pb_type.xml)
is operating in `LUT` mode.

xc7: Use the common_slice definition when LUTRAM used as a LUT.

---

CMakeLists.txt
ice40/utils/ice40_generate_routing.py
ice40/utils/ice40_import_routing_from_icebox.py
xc7/utils/prjxray_create_edges.py
xc7/utils/prjxray_routing_import.py

This PR removes dummy tracks in the routing graph, both for ice40 and xc7.
It fixes https://github.com/SymbiFlow/symbiflow-arch-defs/issues/829, but it can be merged after conda VTR includes the following patch: https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/648.

rr_graph: removing dummy tracks/channels from routing graph

---

common/cmake/devices.cmake

This PR adds the `bounding_box` place algorithm option when creating the virtual rr_graph.
After analyzing why [this VPR patch was needed](https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/664) (issue described [here](https://github.com/SymbiFlow/vtr-verilog-to-routing/issues/76)), I've noticed that the error showed up at the `virtaul_rr_graph` generation moment because the placer was using the `timing_driven` algorithm which, presumably, produces an error if timing information is not correctly provided to the architecture.
[Here there is the code](https://github.com/verilog-to-routing/vtr-verilog-to-routing/blob/4cfe982a6051e5bfe5c19ee1676b9baaa3fbec40/vpr/src/place/place.cpp#L3499-L3514) that produces the error: if …

rr_graph: adding bb place algorithm when creating rr_graph virt

---

CMakeLists.txt
common/cmake/devices.cmake
ice40/icestorm.cmake
testarch/CMakeLists.txt
xc7/make/arch_define.cmake

This PR adds the option to allow dangling combinational nodes to xc7.
CI will fail as the option is not yet in the conda package. Once it is added I will re-run kokoro and merge if green.

cmake: update VTR and add new command line options

---

common/xml/routing_resource.xsd
utils/lib/rr_graph/graph.py

This:
- Converts all `xs:double` types to `xs:float` in accordance with VPR's usage.
- Converts fields for some of the index types from `xs:int` to `xs:unsignedInt`. Not all are converted because `-1` is a special value in some fields such as node segment_ids.
- Deletes `x_offset` and `y_offset` attributes from metadata.
- Converts `xs:choice`s to `xs:all` where applicable. `xs:choice` does not imply existence of all elements inside it, but we need that behavior in some places like the top-level tag.

Revise rr_graph schema

---

xc7/fasm2bels/clb_models.py

Unused CIN or CYINIT of a CARRY4 was left unconnected. This caused Yosys simulation to crash and caused Icarus to produce Xs. This happened eg, on autosim target in xc7/tests/counter design.
This PR ties those inputs to const 0 when unused which fixes the problem.

Fix unconnected CARRY4 inputs in fasm2bels

---

utils/update_arch_timings.py
xc7/bels.json

This PR introduces a change to the `bels.json` format thus allowing to explicitly specify which SDF CELLs and in what order to import.
SDF CELLs are now specified as a list of CELLTYPE.INSTANCE, not as independent list of CELLTYPEs and INSTANCEs. Timings from multiple CELLs are merged as it was done before, but now in the order from last to first. This means that if there are multiple CELLs which specify the same timing, the former ones will take precedence over the latter ones.
For example, in an SDF we have:
```
(CELL
(CELLTYPE "LUT_OR_MEM6LRAM")
(INSTANCE SLICEM/A6LUT)
(DELAY
(ABSOLUTE
(IOPATH A1 O6 (0.045::0.056)(0.100::0.124))
(IOPATH A2 O6 (0.045::0.056)(0.100::0.124))
(IOPATH A3 O6 (0.045::0.056)(0.100::0.124))
(IOPATH A4 O6 (0.045::0.056)(0.100::0.124))
(IOPATH A5 O6 …
```

Refactored timing import with explicit CELL specification and order.

---

xc7/bels.json
xc7/primitives/slicem/srl/srlc32e_vpr.model.xml
xc7/primitives/slicem/srl/srlc32e_vpr.pb_type.xml

This PR adds timings to SRL32 definitions. It also fixes a bug in `update_arch_timings.py` which caused hold times to be imported incorrectly.
Due to lack of support of a particular timing model structure in VPR (see https://github.com/SymbiFlow/symbiflow-arch-defs/issues/958) the output Q is treated as combinational and dependent on A inputs.

SRL32 timings

---

xc7/README.md

The git checkout should be git clone.

Fixes "git checkout" typo to "git clone"

---

xc7/make/arch_define.cmake
xc7/make/device_define.cmake

This PR is to solve the last thing on the todo list in #418.
Namelly: Use tool from SymbiFlow/prjxray#694 to create bitstream from frames, rather than patching design.bit with xc7patch.

xc7: Switch to xc7frames2bit for bitstream generation

---

common/xml/fpga_architecture.xsd

Fixes the following issues found in the schema when generating a parser using [uxsdcxx](https://github.com/duck2/uxsdcxx/);

Revise arch schema

---

.github/kokoro/continuous-docs.cfg
.github/kokoro/continuous-ice40.cfg
.github/kokoro/continuous-testarch.cfg
.github/kokoro/continuous-tests.cfg
.github/kokoro/continuous-xc7.cfg
.github/kokoro/kokoro-cfg.py
.github/kokoro/presubmit-docs.cfg
.github/kokoro/presubmit-ice40.cfg
.github/kokoro/presubmit-testarch.cfg
.github/kokoro/presubmit-tests.cfg
.github/kokoro/presubmit-xc7.cfg
.github/kokoro/steps/hostsetup.sh
.github/kokoro/xc7.sh
Makefile

Unclear why, but using ninja might help with the flakyness we've been seeing on the large VMs.  It may also speed up builds too.  As a side affect, ninja logs can be used to easily profiler the build times (see https://buildbloat.neocities.org/)

Use ninja build system.

---

utils/vlog/yosys/json.py

Comment says that the cell property does not include Yosys internal cells, but the code is not filtering them.

Yosys: cells property should not return internal cells

---

xc7/tests/dram_test/dram_test_64x1d.v

- Trailing commas are not standard, remove them.
- error checker is assuming registered RAM, add register to LUT-RAM.

Fixes some issues with 64x1D test.

---

CMakeLists.txt
xc7/archs/artix7/devices/CMakeLists.txt
xc7/archs/artix7/devices/xc7a50t-arty-swbut-roi-virt/CMakeLists.txt
xc7/archs/artix7/devices/xc7a50t-arty-uart-roi-virt/CMakeLists.txt
xc7/boards.cmake
xc7/tests/buttons/CMakeLists.txt
xc7/tests/buttons/arty.pcf
xc7/tests/buttons/buttons_arty.v
xc7/tests/counter/CMakeLists.txt
xc7/tests/uart_loopback/CMakeLists.txt

This adds an `arty-swbut` board(separate from `arty`, which uses `uart` harness) which uses the `swbut` harness of Arty, and adds a case to `xc7/tests/buttons` so that `make buttons_arty_prog` works on HW.

Add buttons_arty target

---

tests/9-scalable_proc/utils/rom_generator.py
xc7/bels.json
xc7/fasm2bels/clb_models.py
xc7/fasm2bels/verilog_modeling.py
xc7/primitives/slicem/Ndram/d_dram.pb_type.xml
xc7/primitives/slicem/Ndram/dpram32.pb_type.xml
xc7/primitives/slicem/Ndram/ntemplate.N_dram.pb_type.xml
xc7/primitives/slicem/slicem.pb_type.xml
xc7/primitives/slicem/srl/a_srl.pb_type.xml
xc7/primitives/slicem/srl/ntemplate.N_srl.pb_type.xml
xc7/techmap/cells_map.v
xc7/tests/dram_test/CMakeLists.txt
xc7/tests/dram_test/dram_test_32x1d.v
xc7/tests/dram_test/dram_test_64m.v
xc7/tests/srl/srl32_chain/basys3_top.v

These fixes were identified via fasm2v differences between VPR and Vivado or errors during Vivado.

[xc7] Fixes for SRL and LUT-RAM

---

testarch/utils/testarch_graph.py
utils/lib/rr_graph/tests/test_tracks.py
utils/lib/rr_graph/tracks.py
xc7/utils/prjxray_assign_tile_pin_direction.py
xc7/utils/prjxray_create_edges.py
xc7/utils/prjxray_form_channels.py
xc7/utils/prjxray_routing_import.py

During edge creation, get_tracks_for_wire_at_coord gets called enough
times that caching the result is a good memory <-> CPU trade off.
Part of prjxray_create_edge scaling work to reach full 50T in reasonable time.

Refactor tracks to cache neighboor computation.

---

xc7/boards.cmake
xc7/make/device_define.cmake
xc7/make/project_xray.cmake
xc7/tests/buttons/CMakeLists.txt
xc7/tests/buttons/basys3_x1y0.pcf
xc7/tests/buttons/buttons_basys3_x1y0.v
xc7/utils/prjxray_arch_import.py
xc7/utils/prjxray_create_edges.py
xc7/utils/prjxray_create_pinmap_csv.py
xc7/utils/prjxray_form_channels.py
xc7/utils/prjxray_routing_import.py
xc7/utils/prjxray_tile_import.py

This PR will hopefully add support for routing to RIOB33M pins.
Approximate work:

Initial support for RIOB33M routing

---

xc7/utils/prjxray_edge_library.py

These bugs were discovered when debugging ROI-less clock routing (e.g. #1060).
Changes:
- Do not emit pip_pkey on site pin CHAN to IPIN/OPIN.
- Handle case of dead tracks with bidirection pips.
- Handle walking down nodes that span multiple tiles.

Fixes to create edges

---

CMakeLists.txt

Superceeds #1064 
FYI @acomodi and @mkurc-ant , the update_tools.py will not include all branches if a merge conflict is detected during the octopus merge.

Update VTR package to latest

---

utils/update_tools/update_tools.py

This PR fixes https://github.com/SymbiFlow/symbiflow-arch-defs/issues/1068. The strategy now is to fallback to a Sequential merge of all the `wip/` branches whenever there is a conflict during the Octopus Merge.
In this way we are sure that all the branches are included in the `master+wip-next` branch.

update_tool: fixed wrong Octopus merge when having conflicts

---

testarch/utils/testarch_graph.py
utils/lib/perf_utils.py
utils/lib/rr_graph_xml/graph2.py
xc7/fasm2bels/fasm2bels.py
xc7/utils/prjxray_routing_import.py

This PR adds optimizations to the `prjxray_routing_import.py` functionality allowing to significantly reduce its memory footprint. 
Before the optimization import of routing for the whole 50T rr graph took **18.5 GB** and **336 sec**. Once they are applied it takes only **3.6 GB** and **397 sec** (the db read from a HDD drive).
The optimizations include:
- Removal of loading of the whole rr graph to memory at once in favor of parsing it iteratively. Also the data is not stored in ET.Element objects which are pretty memory consuming.
- Refactored rr graph serialization so the data is directly written into the XML file rather than being stored in ET.Element objects and then serialized.
- Removal of SQL database cache. The database is read from the file directly.
This PR also adds a memory …

Routing import memory optimizations

---

xc7/utils/prjxray_create_edges.py
xc7/utils/prjxray_define_segments.py
xc7/utils/prjxray_edge_library.py

- The lookahead expansion is currently driven based on the order of segments,
so to ensure consistent behavior, the order of segments should be fixed
rather than simply based on the hash order.
- CCIO wires are fairly special (dedicated routing to BUFG, etc), and
should be handled specially.  By defining a segment for CCIO IPINs
(rather than the generic OUTPINFEED) this ensures they get full
characterization.

Fix the order segments via an OrderedDict and add CCIO segments.

---

CMakeLists.txt
utils/lib/rr_graph/graph2.py
utils/lib/rr_graph_xml/graph2.py
xc7/fasm2bels/fasm2bels.py
xc7/fasm2bels/net_map.py
xc7/make/arch_define.cmake
xc7/make/project_xray.cmake
xc7/utils/prjxray_routing_import.py

- This PR introduces rr node re-sorting based on a Hilbert curve, which
is a space filing curve.  This change dramatically speeds up expansion
in the lookahead for the full 50T graph (3600 -> 600 seconds).
It should also accelerate routing in general on graphs, but this has
not been tested.

Sort rr node ids by geometric neighbors.

---

xc7/utils/animate_router_pop.py
xc7/utils/annotate_vpr_log.py

- annotate_vpr_log.py is designed to convert vpr logs (like the detailed
routing diagnostic output) and change rr node ids to wire names.
- animate_router_pop.py is designed create a simple Vivado tcl script for
animating the router search behavior for visualizing the VPR router behavior.

Add xc7 two router diagnostic tooling

---

xc7/fasm2bels/clb_models.py
xc7/fasm2bels/cmt_models.py
xc7/fasm2bels/fasm2bels.py
xc7/fasm2bels/iob_models.py
xc7/fasm2bels/make_routes.py
xc7/fasm2bels/verilog_modeling.py

This PR adds support for the PLLE2_ADV decoding to fasm2bels. Requires https://github.com/SymbiFlow/prjxray/pull/1077 to work correctly (routing decoding issues).
The decoding of COMPENSATION parameter may require improvement as the relation between fasm tags and this parameter is somewhat unclear.

Support for PLLE2_ADV for fasm2bels.

---

xc7/bels.json
xc7/primitives/slicem/Ndram/dpram32.pb_type.xml
xc7/primitives/slicem/Ndram/dpram64.pb_type.xml
xc7/primitives/slicem/Ndram/dpram64_for_ram128x1d.pb_type.xml
xc7/primitives/slicem/Ndram/ntemplate.N_dram.model.xml

This PR adds timings injection to DRAM pb_types. Also, it modifies the DRAM models removing combinational connection of write port signals to output (the docs says all writes are sequential/reads are combinational)

xc7: fix dram timings and models

---

utils/lib/rr_graph/graph2.py
utils/lib/rr_graph_xml/graph2.py
xc7/utils/prjxray_routing_import.py

This is important because the generic delay matrix doesn't account for
per site pin delays.  By adding an annotation of the portion of the IPIN
that varies dramatically (and varies at the end of the route and is
unaviodable), it enables the connection box lookahead to properly
account for this delay.
See https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1027
for more details and examples.

Add site pin delay to connection box annotation.

---

Makefile

Signed-off-by: Andrew Plumb <andrew@plumb.org>
Tweaks to the Makefile to allow for alternate cmake paths, needed on the RedHat systems at work.
Signed-off-by: Andrew Plumb <andrew@plumb.org>

Makefile tweaks to allow for alternate cmake paths.

---

utils/update_tools/update_tools.py

The previous version of update_tools maintained a simplified history by force pushing overtop of `master+wip` and `master+wip-next`.  This results in github PRs not working correctly, and continuously orphaning trees.
This approach avoids the force push by making a revert commit to `master+wip`, and then merging with `master`.  This achieves the original goal of keeping the history sane, but avoids orphaning the old `master+wip` integration point.
See https://github.com/SymbiFlow/vtr-verilog-to-routing/pull/319 as an example PR with this new methodology.

Change update_tools to avoid requiring force pushes all the time.

---

.github/kokoro/xc7-vendor.sh
xc7/make/vivado.cmake
xc7/tests/buttons/CMakeLists.txt
xc7/tests/counter/CMakeLists.txt
xc7/tests/pll/CMakeLists.txt
xc7/tests/simple_ff/CMakeLists.txt
xc7/tests/srl/srl16_chain/CMakeLists.txt
xc7/tests/srl/srl32_amc31/CMakeLists.txt
xc7/tests/srl/srl32_chain/CMakeLists.txt
xc7/tests/srl/srl32_shift/CMakeLists.txt

Disabled tests:
Because of https://github.com/SymbiFlow/symbiflow-arch-defs/issues/1019:
- srl16_chain
- srl32_doutmux_mc31
- srl32_chain
- srl32_shift
Unknown failures:
- buttons_basys3
- counter_basys3
- simple_ff
Because of Vivado clock routing violations:
- pll_int_basys3_x1y0
- pll_buf_basys3_x1y0
- pll_ext_basys3_x1y0

[xc7] Enable all working FASM diff tests, disable failing tests

---

xc7/make/arch_define.cmake

This PR is needed to have the packer not failing during the OSERDES clustering.
The problem should still be solved to be able to re-enable the filter, which will reduce the packer run-time

xc7-arch: disable pin feasibility filter once again

---

xc7/make/project_xray.cmake
xc7/utils/prjxray_create_equiv_tiles.py
xc7/utils/prjxray_physical_tile_import.py

This PR is to remove the "priority" from the tiles in the architecture XML as it is not needed.

arch: remove priority from physical tiles

---

CMakeLists.txt
tests/9-soc/murax/CMakeLists.txt
tests/9-soc/picosoc/CMakeLists.txt
xc7/make/arch_define.cmake
xc7/utils/prjxray_edge_library.py

- Use bounded base costs for routing (but not for the lookahead)
- Increase the initial present congestion factor from 0.5 to 4
- Disable incremental ripup
- Use median segment lengths for computing segments lengths, instead of mean

Increase initial pres

---

CMakeLists.txt
xc7/utils/prjxray_create_equiv_tiles.py
xc7/utils/prjxray_physical_tile_import.py

This PR is to add the `pin_mapping` attribute to the `site` tag in the `equivalent_sites` list of each tile.
CI fail due to the fact that `master+wip` VtR does not yet include the latest equivalent sites changes. Once the conda-environment will be updated with the new revision of VtR, CI will turn green.

Update VtR with new-equivalent-tiles integration

---

xc7/utils/prjxray_edge_library.py

LV#.LV## is the same as LV#.LV#, so it sorts lexigraphically.
SW#BEG.SE#END0_S# is greater than SW#BEG.SE#END#.

Use length of pip names without trailing numbers.

---

xc7/utils/prjxray_edge_library.py
xc7/utils/prjxray_find_inode.py

This fixes the `IDELAYCTRL.RDY` and `IDELAYCTRL.RST`graph connections.

Fix site pin switch when connecting pip is in another tile.

---

xc7/fasm2bels/ioi_models.py
xc7/primitives/ilogice3/ilogice3.pb_type.xml
xc7/techmap/cells_map.v
xc7/techmap/cells_sim.v

This PR adds additional features for the ISERDES that were missing.
It also adds some parameters in the techmap which are left as default ones for IDELAY and ISERDES:
- SERDES_MODE
- REFCLK_FREQUENCY
- SIGNAL_PATTERN

iserdes: add missing features

---

tests/9-soc/murax/CMakeLists.txt
tests/9-soc/picosoc/CMakeLists.txt

This makes picosoc route in ~30 seconds and murax in ~18 seconds

soc tests: added sdc file to picosoc and murax on 50T

---

CMakeLists.txt
utils/eblif.py
utils/lib/connection_database.sql
utils/vpr_place_constraints.py
xc7/make/arch_define.cmake
xc7/tests/serdes/CMakeLists.txt
xc7/utils/prjxray_create_place_constraints.py
xc7/utils/prjxray_form_channels.py

This PR builds on top of https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1232 as a fix for the python linter was needed.
With prjxray ad prjxray-db updated to latest version, containing the clock_region addition, this PR should now go green.

[xc7] Add clock placer

---

xc7/fasm2bels/connection_db_utils.py
xc7/fasm2bels/fasm2bels.py
xc7/fasm2bels/hclk_ioi3_models.py
xc7/fasm2bels/iob_models.py

This PR fixes handling of some pips/wires that are named differently for `[LR]IOI3_SING` tiles. Basically undoes wire renaming in fasm2bels flow that was introduced by https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1242
Also fixes bugs with setting of the `IN_TERM` parameter on top-level ports.

Fixes for fasm2bels

---

xc7/fasm2bels/ioi_models.py
xc7/tests/serdes/serdes_test_idelay.v

This PR fixes an issue in IDELAYs for which, in some cases, their instantiation was skipped in fasm2bels.

idelay: fixed fasm2bels issue

---

xc7/make/arch_define.cmake

The clsuter pin feasibility filter should be re-enabled to have faster packing.

xc7: re-added cluster feasibility pin

---

common/xml/routing_resource.xsd
utils/lib/connection_database.py
utils/lib/connection_database.sql
utils/lib/rr_graph/graph2.py
utils/lib/rr_graph/tests/test_graph2.py
utils/lib/rr_graph_xml/graph2.py
xc7/utils/prjxray_arch_import.py
xc7/utils/prjxray_edge_library.py
xc7/utils/prjxray_form_channels.py
xc7/utils/prjxray_routing_import.py

This PR adds a `delayfull` switch that has an intrinsic `fake` delay that forces the router to take other paths.
This should solve https://github.com/SymbiFlow/symbiflow-arch-defs/issues/1153 and https://github.com/SymbiFlow/symbiflow-arch-defs/issues/1019

Add penalty cost switch to avoid wrong routes

---

CMakeLists.txt
common/cmake/devices.cmake
testarch/devices/CMakeLists.txt

The incremental XML writer we use during rr graph patching is actually
pretty memory efficent, so for now I don't see a reason to do anything
other than to write XML first, then convert to capnp using VPR.

Convert from rrgraph XML to capnp during lookahead computation.

---

xc7/tests/iobuf_i2c/CMakeLists.txt
xc7/tests/iobuf_i2c/basys3.sdc

This PR is to check whether the clock to general interconnect issue can be solved also by adding SDC files to constrain the clock.

add sdc file to iobuf_i2c test

---

xc7/utils/prjxray_make_ps7_models.py

This is a script that reads the `ps7_ports.json` (meant to be in the prjxray database https://github.com/SymbiFlow/prjxray/pull/1170) and basing on it generates:
- XML model of the PS7 for the VPR
- XML pb_type of the PS7 for the VPR
- The PS7 cell verilog blackbox
- A techmap that converts `PS7` to `PS7_VPR` and ties all unconnected input ports to GND in the same way as the vendor tools do.
This script was used to generate all of the above that are present in arch defs right now. We might consider generating these instead of keeping it hard-coded in the future.

A script for the PS7 cell

---

xc7/fasm2bels/iob_models.py

This PR is to fix an issue in fasm2bels for which, if the IOSTANDARD is set to `SSTL135`, which should have no DRIVE setting, the correct settings would not end up in the resulting verilog file, causing an issue in Vivado.
With this PR, whenever the SSTL135 setting is active, the DRIVE setting is set to `None`.
There is also a simplification of the INOUT regexp when building the `iosettings_map`

Fix iostandard fasm2bels

---

utils/lib/rr_graph/graph2.py
utils/lib/rr_graph_xml/graph2.py

This PR adds optional loading of VPR rr graph edges. By default they are not loaded. It also adds loading segment_id for rr graph nodes.

Added optional loading rr graph edges to the graph library

---

common/cmake/devices.cmake
xc7/make/arch_define.cmake

Clean up unnecessary flags, and enable `--quick_check_route`.

Remove VPR flags set to default values, and set --quick_check_route

---

xc7/techmap/cells_map.v

This PR fixes a bug related to the `IS_T{N}_INVERTED` parameter during techmap of OSERDESes.

oserdes: fix IS_T_INVERTED parameter

---

xc7/fasm2bels/clb_models.py

Apparently the `IS_C_INVERTED` parameter for the LDCE does not exist. In fact, I get the following when building a fasm2bels generated verilog file:
```
ERROR: [Synth 8-3438] module 'LDCE' declared at '/opt/Xilinx/Vivado/2017.2/scripts/rt/data/unisim_comp.v:20239' does not have any parameter 'IS_C_INVERTED' used as named parameter override [symbiflow/prjxray/minitests/f2b_vivado/build/top_bit.v:89128]
```

fasm2bels: fix LDCE is_c_inverted

---

xc7/make/arch_define.cmake

These warnings are now being generated since check route is running.
For context without this there are ~50k lines saying something to affect of:
```
Warning 17512: in check_route: found non-adjacent segments in traceback while checking net 6591:
RR node: 863411 type: CHANY location: (96,14) track: 393 len: 0 longline: 0 seg_type: FAN_BOUNCE dir: BI_DIR capacity: 1
RR node: 801604 type: CHANY location: (95,14) track: 61 len: 0 longline: 0 seg_type: INPINFEED dir: BI_DIR capacity: 1
```
Which is totally meaningless for our graph.

Suppress useless warnings from check_route.

---

CMakeLists.txt
xc7/tests/ddr/arty.sdc
xc7/tests/ddr/ddr_uart.v

This is a workaround for the VPR bug between SDC constraints and net aliases for the DDR uart test, until VPR is fixed.

Refactor SDC to avoid VPR net aliases.

---

xc7/utils/prjxray_form_channels.py

This helps avoid the BUFHCE chaining we've seen.

Add penalty to edges that enable HCLK loopbacks.

---

CMakeLists.txt
common/cmake/devices.cmake
xc7/make/arch_define.cmake

As part of upstream PRs being accepted some flags were renamed for
clarity.

Use latest VtR from conda and update flags.

---

.github/travis/script.sh
.travis.yml
CMakeLists.txt

This PR updates the minimum CMake version required.  This should solve https://github.com/SymbiFlow/symbiflow-arch-defs/issues/1370#issuecomment-602045210

cmake: update minimum version to 3.14.0

---

CMakeLists.txt
common/xml/fpga_architecture.xsd
utils/lib/pb_type_xml.py
utils/update_arch_tiles.py
xc/common/cmake/arch_define.cmake
xc/common/cmake/project_ray.cmake
xc/common/utils/prjxray_arch_import.py
xc/common/utils/prjxray_create_equiv_tiles.py
xc/common/utils/prjxray_create_place_constraints.py
xc/common/utils/prjxray_import_tile_capacity.py
xc/common/utils/prjxray_physical_tile_import.py
xc/common/utils/prjxray_tile_import.py
xc/xc7/archs/artix7/tiles/clk_bufg_bot_r/CMakeLists.txt
xc/xc7/archs/artix7/tiles/clk_bufg_top_r/CMakeLists.txt
xc/xc7/archs/artix7_200t/tiles/clk_bufg_bot_r/CMakeLists.txt
xc/xc7/archs/artix7_200t/tiles/clk_bufg_top_r/CMakeLists.txt
xc/xc7/archs/zynq7/tiles/clk_bufg_bot_r/CMakeLists.txt
xc/xc7/archs/zynq7/tiles/clk_bufg_top_r/CMakeLists.txt
xc/xc7/tests/bram_test/CMakeLists.txt

This PR is an initial implementation of the heterogeneous tiles introduced with https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/1208.
TODO:

Heterogeneous tiles implementation

---

.gitattributes

GitHub uses https://github.com/github/linguist to do language stats. linguist however mis-detects a bunch of things in this repo. It also needs to be told about the "vendored" files in the repo.
This can be fixed by setting values via `.gitattributes` file which is done here.
```
52.90%  Coq
24.67%  Python
15.74%  Verilog
5.54%   CMake
0.46%   Shell
0.25%   C
0.23%   PLSQL
0.12%   Tcl
0.05%   Makefile
0.04%   Assembly
```
```
57.04%  Python
28.79%  Verilog
12.71%  CMake
1.08%   Shell
0.29%   Tcl
0.10%   Makefile
```

Add .gitattributes so GitHub gets the language right.

---

utils/vpr_place_view.py

This is a small utility script I wrote. It allows to visualize VPR placement by parsing the `.place` file only.
An example visualization (this is for Quicklogic EOS S3):

A VPR placement visualization utility.

---

.github/kokoro/continuous-xc7-vendor.cfg
.github/kokoro/presubmit-xc7-vendor.cfg
CMakeLists.txt
xc/common/cmake/arch_define.cmake
xc/common/primitives/bufgctrl/bufgctrl.model.xml
xc/common/primitives/bufgctrl/bufgctrl.pb_type.xml
xc/common/primitives/plle2_adv/plle2_adv.model.xml
xc/common/primitives/plle2_adv/plle2_adv.pb_type.xml

This PR changes the way PLL and BUFGCTRL model is defined:
- PLL: remove the combinational sink from CLKIN to CLKOUTs. This allows not to use the VPR wip branch `revert_clock_propagation`. The downside though is that the delay constants in the pb_type cannot be used anymore, as there is no combinational sink in the model for the clock signals.
- BUFGCTRL: remove the `is_clock` attribute from the clock output, as the clock path should be detected by the timing graph build step.
This PR needs to have a new VtR master+wip with the `wip/revert_clock_propagation` branch removed from the octopus merge.

Update to latest VtR

---

xc/xc7/toolchain_wrappers/vpr_common

install: allow override of VPR options

---

CMakeLists.txt
common/cmake/env.cmake

Hello all!
We are seeing some build issues on OpenSuse and Arch. When running `make all_conda`, we encountered the following error:
```
g++ -pthread -shared -B /scratch/safe/syed/dev/symbiflow-arch-defs/build/env/conda/compiler_compat -L/scratch/safe/syed/dev/symbiflow-arch-defs/build/env/conda/lib -Wl,-rpath=/scratch/safe/syed/dev/symbiflow-arch-defs/build/env/conda/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/pyjson5.o -o build/lib.linux-x86_64-3.7/pyjson5.cpython-37m-x86_64-linux-gnu.so -std=c++11 -O2 -fPIC -ggdb1 -pipe -fomit-frame-pointer -fstack-protector-strong
/scratch/safe/syed/dev/symbiflow-arch-defs/build/env/conda/compiler_compat/ld: build/temp.linux-x86_64-3.7/pyjson5.o: unable to initialize decompress status for section .debug_info …
```

Upgrades miniconda and pycapn

---

CMakeLists.txt
xc/common/utils/prjxray_arch_import.py

This PR bumps VPR to the recent master+wip with post synthesis netlist write fix (analysis targets work). Also suppresses emission of `__vpr_delayless_switch__` to the arch.xml. It is now implicitly defined.

Bump VPR + delayless switch fix

---

utils/vpr_io_place.py
utils/vpr_place_constraints.py

This commit changes the architecture importing scripts and allows them to parse huge .net files. Without these changes, libxml fails on using XPath expressions due to the internal memory allocation limit. In that situation, the python wrapper on the libxml library throws misleading error message about incorrect XPath expression.
This changes are required for OpenTitan and are related to https://github.com/SymbiFlow/symbiflow-arch-defs/issues/1442#issuecomment-619055675

Allow import scripts to parse huge .net files

---

README.md

The documentation of the "Xilinx Series 7" was relocated in commit:
a1ab7beb03c8f7ef6756b94fddc4e0d947832a67
Adjust the reference accordingly.
Signed-off-by: Marcello Sylvester Bauer <sylv@sylv.io>

README.md: Update reference to xc7

---

xc/common/utils/prjxray_create_synth_tiles.py

Signed-off-by: Andrew Butt <andrewb1999@gmail.com>
Filters NULL tile types when mapping synth tiles to vpr coordinates.  Fixes #1538

Filter NULL tiles in synth tile map to vpr coord

---

xc/xc7/fasm2bels/clb_models.py

This PR fixes the DOUTMUX connection of SLICEs when CARRY primitives are used. Related issue: https://github.com/SymbiFlow/yosys/pull/81#issuecomment-652942817.

fasm2bels: clb: fix carry chain DOUTMUX connections

---

common/cmake/devices.cmake
utils/vpr_io_place.py
xc/common/cmake/arch_define.cmake
xc/common/utils/prjxray_create_ioplace.py
xc/xc7/fasm2bels/fasm2bels.py
xc/xc7/techmap/cells_map.v
xc/xc7/tests/soc/litex/mini_ddr/CMakeLists.txt
xc/xc7/tests/soc/litex/mini_ddr/minilitex_ddr_arty.xdc

This PR adds support for the LOC properties read from XDC (addresses issue #1471). 
The enhanced XDC Yosys plugin processes the LOC property settings from the XDC file (look [PR](https://github.com/SymbiFlow/yosys-symbiflow-plugins/pull/16)). 
The IO constraints land in the eblif in form of LOC parameters for each IOBUF subckt.
The IoPlace class got enhanced to parse the settings and populate a net_to_pads set which made the pcf parser redundant.
The CI will fail until the new XDC plugin is in place. 
minilitex_ddr_arty test has been modified to take the LOC settings from XDC instead of PCF.

Support for IO constraints read from XDC

---

xc/common/cmake/device_define.cmake
xc/common/utils/prjxray_create_place_constraints.py
xc/xc7/archs/artix7/devices/xc7a50t-bottom-virt/CMakeLists.txt

This commit adds the ability to verify if the clock location is available in the FPGA grid before placement. It uses architecture XML for the verification.
Resolves https://github.com/SymbiFlow/symbiflow-arch-defs/issues/1517

Fix clock placement in devices with limited grid

---

xc/common/cmake/arch_define.cmake
xc/common/cmake/vivado.cmake
xc/common/utils/vivado_create_runme.py
xc/xc7/fasm2bels/fasm2bels.py
xc/xc7/fasm2bels/make_routes.py
xc/xc7/fasm2bels/verilog_modeling.py

This PR is an initial work to have the XDC constraints, which will allow for faster fasm2bels step.
On an initial test (counter) everything seems to be working all right except for the CLK net constraints.
In fact, the XDC clock for a net constraints look like the following (this is generated by doing `write_xdc` on an implemented design from the old fasm2bels:
```
set_property FIXED_ROUTE { { CLK_HROW_CK_HCLK_OUT_L9 CLK_HROW_CK_BUFHCLK_L9 <8>HCLK_LEAF_CLK_B_TOPL3  { <7>GCLK_L_B9_WEST CLK_L1 CLBLL_LL_CLK }   { <4>GCLK_L_B9_WEST CLK_L1 CLBLL_LL_CLK }   { <8>GCLK_L_B9_WEST  CLK_L1 CLBLL_LL_CLK }   { <5>GCLK_L_B9_WEST CLK_L1 CLBLL_LL_CLK }   { <9>GCLK_L_B9_WEST CLK_L1 CLBLL_LL_CLK }   { <6>GCLK_L_B9_WEST CLK_L1 CLBLL_LL_CLK }  <3>GCLK_L_B9_WEST  { CLK_L1 CLBLL_LL_CLK }  CLK_L0 …
```

Transition to use XDC constraints instead of TCL in fasm2bels

---

tests/9-soc/picosoc/CMakeLists.txt
xc/xc7/archs/artix7_200t/devices/CMakeLists.txt
xc/xc7/archs/artix7_200t/devices/xc7a200t-mid-virt/CMakeLists.txt
xc/xc7/boards.cmake

This commit defines A200T device with an excluded bottom row with GTP tiles

Define A200T device with limited grid

---

xc/common/cmake/device_define.cmake
xc/common/cmake/project_ray.cmake
xc/common/utils/prjxray_create_synth_tiles.py

Signed-off-by: Andrew Butt <butta@seas.upenn.edu>
Allows easier custom partition region/roi synth tile creation by automatically picking the correct synth tile wire from only a vivado node name.

Add support for synth tiles creation from vivado node names only

---

README.md

All the badges should be accessible in the symbiflow-badges GCS bucket.
*Really* fixes https://github.com/SymbiFlow/symbiflow-arch-defs/issues/1450

Fix the build badges.

---

xc/common/cmake/arch_define.cmake

This is to avoid VPR printing out tons of warnings related to "Inconsistent buffering of rr nodes .."
Output example:
```
Warning 65: Inconsitent buffering of children of rr node OUTPINFEED (RR node: 1316 type: CHANX location: (7,2) <-> (9,2) track: 165 len: 2 longline: 0 seg_type: OUTPINFEED dir: BI_DIR capacity: 1)
Warning 66: Inconsitent buffering of children of rr node OUTPINFEED (RR node: 1317 type: CHANX location: (7,2) <-> (9,2) track: 164 len: 2 longline: 0 seg_type: OUTPINFEED dir: BI_DIR capacity: 1)
Warning 67: Inconsitent buffering of children of rr node OUTPINFEED (RR node: 1318 type: CHANX location: (7,2) <-> (9,2) track: 163 len: 2 longline: 0 seg_type: OUTPINFEED dir: BI_DIR capacity: 1)
Warning 68: Inconsitent …
```

xc7: cmake: add calculate_average_switch func to warning ignore list

---

xc/common/cmake/vivado.cmake
xc/common/utils/vivado_create_runme.py

The add_vivado_pnr targets are intended to run a full Vivado based P&R flow, rather than just the fasm2bels into DCP flow.

Do full P&R flow when requested.

---

common/cmake/devices.cmake

This PR fixes https://github.com/SymbiFlow/symbiflow-arch-defs/issues/1656

devices.cmake: remove OUT_MERGED_FASM before appending fasm files

---

xc/xc7/tests/ddr/ddr_uart_100t.v

Signed-off-by: Tim Callahan <tcal@google.com>

Remove stragler PLL LOC constraint for 100T -- no longer necessary.

---

xc/CMakeLists.txt
xc/common/cmake/arch_define.cmake
xc/common/cmake/vivado.cmake

This adds CMake logic to invoke the interchange and create DCPs with RapidWright, but leaves that logic dormant unless RAPIDWRIGHT_PATH is supplied pointing to an version of RapidWright with the interchange support present.

Begin integration of new fasm2bels with interchange support

---

xc/xc7/tests/soc/ibex/ibex.patch
xc/xc7/yosys/utils.tcl

This PR:
- adds the `CLKFBOUT_PHASE` parameter to the list of updated PLL parameters.
- improves formatting in the `utils.tcl` script (previously mix of tabs and spaces)
- updates the ibex.patch
After the update, Ibex works on HW.
This issue has been tracked on our burndown list. After merging, I will update the list.

Fix missing CLKFBOUT_PHASE update

---

xc/xc7/tests/install_test/Makefile
xc/xc7/toolchain_wrappers/symbiflow_pack
xc/xc7/toolchain_wrappers/symbiflow_place
xc/xc7/toolchain_wrappers/symbiflow_route
xc/xc7/toolchain_wrappers/symbiflow_write_fasm
xc/xc7/toolchain_wrappers/symbiflow_write_xml_rr_graph
xc/xc7/toolchain_wrappers/vpr_common

This PR replaces usage of environment variable ``${VPR_SEED}`` to set vpr seed with ``-a``/``--additional_vpr_options`` options added to vpr argument parser. This will allow to add, not only vpr seed, but also another vpr options to the default vpr options.
Signed-off-by: Kamil Rakoczy <krakoczy@antmicro.com>

toolchain_wrappers: add additional_vpr_options option

---

xc/common/cmake/arch_define.cmake
xc/common/cmake/device_define.cmake
xc/common/utils/prjxray_create_synth_tiles.py
xc/common/utils/prjxray_edge_library.py

This PR builds on top of https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1666 and is intended to test the extended lookahead map.

Transition to use extended map lookahead

---

utils/lib/connection_database.py
utils/lib/connection_database.sql
utils/lib/rr_graph/graph2.py
utils/lib/rr_graph/tests/test_graph2.py
utils/lib/rr_graph_capnp/graph2.py
utils/lib/rr_graph_xml/graph2.py
xc/common/utils/prjxray_arch_import.py
xc/common/utils/prjxray_form_channels.py
xc/common/utils/prjxray_routing_import.py

This PR is to test whether the absence of the penalty cost still produces issues in routing clocks outside the clock regions through the general interconnect.
Local builds succeeded in the vivado_diff_fasm test, meaning that no violation of clock routing was generated by VPR

Remove penalty cost for undesirable connections

---

xc/common/primitives/idelayctrl/idelayctrl.model.xml
xc/xc7/tests/ddr/ddr_uart.v
xc/xc7/tests/ddr/ddr_uart_100t.v
xc/xc7/tests/idelayctrl/idelayctrl.v
xc/xc7/tests/serdes/serdes_basys3_idelay.v
xc/xc7/tests/serdes/serdes_test_idelay.v
xc/xc7/tests/soc/litex/base/baselitex_arty.v
xc/xc7/tests/soc/litex/base/baselitex_arty100t.v
xc/xc7/tests/soc/litex/mini_ddr/minilitex_ddr_arty.v
xc/xc7/tests/soc/litex/mini_ddr/minilitex_ddr_arty100t.v

This PR enables the never_prune attribute to the IDELAYCTRL so that it does not get pruned by VPR if no output signal is provided.

Add never prune idelayctrl

---

environment.yml

Now that capnproto is in the symbiflow conda repo, conda-forge can be remove
from the channel list again.

Remove conda-forge.

---

environment.yml

This allows using the libxml2 package from anaconda rather than from
symbiflow.
After this is merged, we can remove the libxml2 job from https://github.com/SymbiFlow/conda-packages

Generalize libxml2 package spec now that 2.9.10 is released.

---

common/cmake/devices.cmake
utils/fix_xc7_carry.py
xc/common/cmake/install.cmake
xc/common/primitives/common_slice/carry/CMakeLists.txt
xc/common/primitives/common_slice/carry/carry4_vpr.model.xml
xc/common/primitives/common_slice/carry/carry4_vpr.pb_type.xml
xc/common/primitives/common_slice/carry/carry_cout_plug.sim.v
xc/common/primitives/common_slice/common_slice.model.xml
xc/common/primitives/common_slice/common_slice.pb_type.xml
xc/xc7/techmap/carry_map.v
xc/xc7/techmap/cells_map.v
xc/xc7/techmap/cells_sim.v
xc/xc7/techmap/clean_carry_map.v
xc/xc7/techmap/fix_carry.py
xc/xc7/tests/soc/litex/base/baselitex_arty.xdc
xc/xc7/toolchain_wrappers/symbiflow_synth
xc/xc7/yosys/synth.tcl

This PR attempts to fix #1597 by change the strategy used to decongest SLICEL CARRY4 outputs.  Previously, all ALU CO uses were modeled as a `O ^ S`, but yosys's abc9 pass is now good enough to undo this change.  So rather than continue to try to fight abc9 as it gets better at merging logic, this PR uses a new CARRY4 congestion avoidance strategy.
Changes:
- Yosys arith mapping using upstream CARRY4 mapping
- New pass (implemented as a Python3 script) de-congests O + CO carry rows by using a LUT equation from the inputs
- CARRY4_VPR is modelled as a blackbox instead of a whitebox to prevent abc9 from modifying/swapping outputs during cleanup optimization

Change how CARRY4 modelling is handled

---

.github/workflows/checkstatus.yml

Close #1741
This is a small enhancement to #1719. Currently, if step 'Check status' fails, the CI run is reported as a failure. This PR sets an output variable (`skip`) instead. That variable is used as the `if` condition in all the remaining steps. As a result, CI runs will all be green, unless there is some issue with any of the steps after the first one.

ci/check-status: set-output name=skip

---

.github/workflows/checkstatus.yml

I have noticed that the check-status workflow is executed also on commits that are not on the master branch: 
```
Run curl -fsSL -H 'Accept: application/vnd.github.v3+json' -H 'authorization: Bearer ***' https://api.github.com/repos/SymbiFlow/symbiflow-arch-defs/commits/bc7fc375e24546994db346a7d0b1921740e2c480/status | head -n 2 | tail -n 1 | grep "success" || echo '::set-output name=skip::true'
curl -fsSL -H 'Accept: application/vnd.github.v3+json' -H 'authorization: Bearer ***' https://api.github.com/repos/SymbiFlow/symbiflow-arch-defs/commits/bc7fc375e24546994db346a7d0b1921740e2c480/status | head -n 2 | tail -n 1 | grep "success" || echo '::set-output name=skip::true'
shell: /bin/bash -e ***0***
curl: (23) Failed writing body …
```

gh-actions: run check status only if commit is on master

---

.github/kokoro/ql.sh

`package_results.sh` is removed because it fails if there is nothing to package!

Change ql.sh to just echo a string and exit for now.

---

.github/kokoro/continuous-docs.cfg
.github/kokoro/continuous-ice40.cfg
.github/kokoro/continuous-ql.cfg
.github/kokoro/continuous-testarch.cfg
.github/kokoro/continuous-tests.cfg
.github/kokoro/continuous-xc7-vendor.cfg
.github/kokoro/continuous-xc7.cfg
.github/kokoro/continuous-xc7a200t-vendor.cfg
.github/kokoro/continuous-xc7a200t.cfg
.github/kokoro/kokoro-cfg.py
.github/kokoro/package_results.sh
.github/kokoro/presubmit-docs.cfg
.github/kokoro/presubmit-ice40.cfg
.github/kokoro/presubmit-ql.cfg
.github/kokoro/presubmit-testarch.cfg
.github/kokoro/presubmit-tests.cfg
.github/kokoro/presubmit-xc7-vendor.cfg
.github/kokoro/presubmit-xc7.cfg
.github/kokoro/presubmit-xc7a200t-vendor.cfg
.github/kokoro/presubmit-xc7a200t.cfg

Also fixes script when generating install collection lists.
Cleans up `third_party`, `.git` and `env` directories prior to kokoro doing artifact collection.

Add Vivado logs to captured results for debugging purposes.

---

.github/kokoro/steps/rapidwright.sh

A change on upstream RapidWright was added that depended on a new version of the closed portion of RapidWright, which is resulting in build failures.  For now, fork RapidWright and move the branch point back until the closed portion of RapidWright is updated.

Update SymbiFlow/RapidWright fork instead of directly ingesting upstream

---

.github/kokoro/steps/rapidwright.sh
xc/common/utils/prjxray_routing_import.py

The newest VPR has fixed an issue with IPIN/OPIN RR nodes for which multiple RR nodes were emitted for the same site pin, due to the possible multiple side locations of the pin.
Therefore, with the new VPR, we cannot count on the presence of multiple nodes for the same pin during the routing import, to create the correct connections between the interconnection nodes and the site nodes.
This PR fixes this issue, assigning the same node ID to the directional graph nodes allowing to have multiple CHAN nodes connected to an IPIN/OPIN.
The corresponding VPR issue is the following one: https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1571.
This PR is expected to fail as with the current version of VPR, multiple nodes corresponding to the same site pin are emitted during the …

Fix unroutability issues with new VPR

---

xc/xc7/tests/soc/litex/generate.py

This PR prevents LiteX designs to incur in non-deterministic P&R due to changes in the BIOS (details in https://github.com/SymbiFlow/symbiflow-arch-defs/issues/1788).
With this PR the Build time timestamp is not being added to the mem.init files, but it requires using the latest versions of LiteX, which insert FD primitives in the design.
The FD have been retargeted with a techmap pass in the synth.tcl script as a temporary workaround, as this should rather be a fix to yosys upstream.

litex: do not output timestamp in BIOS

---

xc/xc7/tests/soc/ibex/generate.py

This PR ensures that Ibex sv2v conversion is deterministic, by enforcing the original input file order (used in synthesis).
A file order during the sv2v conversion is important. When a file is provided earlier, it can force sv2v to generate additional
wrappers or resolve some advanced SystemVerilog syntax correctly (i.e., wildcards)

Make Ibex sv2v conversion deterministic

---

.gitmodules
CMakeLists.txt
common/cmake/env.cmake
environment.yml
xc/common/cmake/arch_define.cmake
xc/common/cmake/vivado.cmake
xc/xc7/CMakeLists.txt
xc/xc7/tests/install_test/CMakeLists.txt

This PR is intended to use the conda packages for the prjxray-tools and prjxray-db:
- prjxray-db: instead of the third party dir, it gets the database from the conda-package
- prjxray-tools: locally conflicts with the riscv64-gcc-newlib package from `litex-hub`. The conflicts are being fixes, and once it's done, I will ad the prjxray-tools conda package as well
The reason behind using the conda packages is that both symbiflow-examples and fpga-perf-tool use them, so, to use the same environment.yml file as used in symbiflow-arch-defs, we require having the prjxray packages here as well.

prjxray: use conda package instead of third_party dir

---

.github/check-status/check-status.py
.github/check-status/entrypoint.sh
.github/kokoro/continuous-install-200t.cfg
.github/kokoro/continuous-install.cfg
.github/kokoro/install-200t.sh
.github/kokoro/install.sh
.github/kokoro/kokoro-cfg.py
.github/kokoro/presubmit-install-200t.cfg
.github/kokoro/presubmit-install.cfg
environment.yml
requirements.txt
xc/common/cmake/install.cmake
xc/xc7/toolchain_wrappers/symbiflow_generate_constraints
xc/xc7/toolchain_wrappers/symbiflow_synth

This PR builds on top of https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1731 and it performs the install step on all the devices.
It generates different packages for each device, as well as a package containing the common required scripts/utils (e.g. toolchain_wrappers, yosys scripts, python utils, etc):
The final content uploaded to GCS should look like the following:
- symbidlow-arch-defs-<commit-sha>.tar.xz
- xc7a50t.tar.xz
- xc7a100t.tar.xz
- ...

Restructure install packages

---

common/cmake/devices.cmake

This PR adds the placement constraints to the benchmarks tarball.
There are some tests that strictly require these constraints (e.g. Litex with DDR) to have all the IOs and clock tiles placed correctly, and to pass the symbiflow tests in upstream VTR.

install: circuits: add also place constraints

---

xc/common/cmake/vivado.cmake
xc/common/utils/vivado_create_runme.py

`read_xdc` by default will write back the XDC if it's different.  This is suprising, so add `-no_add` to prevent this.

Use `read_xdc -no_add` to avoid write-back.

---

.github/kokoro/install.sh
.github/kokoro/steps/hostsetup.sh

`xz` takes a while, and `pixz` might drop the runtime by taking advantage of multiple cores.

Use parallel compression

---

xc/xc7/techmap/cells_map.v
xc/xc7/techmap/cells_sim.v

This is a follow-up to https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1813 and fixes one more issue related to the inverted pins of the ODDR.
In fact, depending on which type of the ODDR (`TDDR` or `ODDR`), the inverted pins should have different features:
- TDDR: `ZINV_T`
- ODDR: `IS_D_INVERTED`

oddr: fix inv and zinv techmaps

---

environment.yml

This PR is to update the VTR package that contains the capnp-schema-dir binary to get the location of the schemas.
Fix merged here: https://github.com/litex-hub/litex-conda-eda/pull/58

bump vtr package

---

.github/kokoro/continuous-docs.cfg
.github/kokoro/continuous-ice40.cfg
.github/kokoro/continuous-install-200t.cfg
.github/kokoro/continuous-install.cfg
.github/kokoro/continuous-ql.cfg
.github/kokoro/continuous-testarch.cfg
.github/kokoro/continuous-tests.cfg
.github/kokoro/continuous-xc7-vendor.cfg
.github/kokoro/continuous-xc7.cfg
.github/kokoro/continuous-xc7a200t-vendor.cfg
.github/kokoro/continuous-xc7a200t.cfg
.github/kokoro/kokoro-cfg.py
.github/kokoro/presubmit-docs.cfg
.github/kokoro/presubmit-ice40.cfg
.github/kokoro/presubmit-install-200t.cfg
.github/kokoro/presubmit-install.cfg
.github/kokoro/presubmit-ql.cfg
.github/kokoro/presubmit-testarch.cfg
.github/kokoro/presubmit-tests.cfg
.github/kokoro/presubmit-xc7-vendor.cfg
.github/kokoro/presubmit-xc7.cfg
.github/kokoro/presubmit-xc7a200t-vendor.cfg
.github/kokoro/presubmit-xc7a200t.cfg

This is ~3x current maximum runtime.

Lower timeout to workaround Vivado 2019.2 hang.

---

.github/kokoro/install.sh

Fixes https://github.com/SymbiFlow/symbiflow-arch-defs/issues/1882

install: resolve symlinks before packaging

---

environment.yml

Add dependencies for fasm ANTLR parser to Conda environment.yml, so that `make env` will install these.

Add fasm dependencies to environment.yml

---

utils/fix_xc7_carry.py

This assert will always trigger when accessing the last item from the list.
Signed-off-by: Daniel Schultz <d.schultz@phytec.de>

utils: Fix assertion error

---

tests/9-soc/picosoc/firmware/Makefile

Add mabi option to make the picosoc example build
Fixes #1967

Fix build error with picosoc example

---

xc/xc7/toolchain_wrappers/symbiflow_write_bitstream

DBROOT depends on the DEVICE variable, so we need to be past any code
that set DEVICE before settting DBROOT.
This cause nmigen fail when using the symbiflow toolchain. See:
https://github.com/SymbiFlow/symbiflow-examples/issues/123
This regression was caused in b35514859f7f02c289c2f6bc058fd3ca1c00143b

Define DBROOT after DEVICE is set

---

environment.yml

Due to the fact rapidyaml now has to be build locally, the build fails without the swig package installed. I added this as a dependency for now to make it easier to have the install process work automatically without having to manually install this package.

Updated dependencies to include swig

---

xc/xc7/techmap/cells_map.v

Yosys throws following error:
Parameter x with non-constant value!
This only happens on localparams which are included in a generate if block.
Move the localparam statement out of the generate fixes the issue.
Closes #2020 
Does not feel right to add nested "? :" statement but do not know a better solution for else if blocks.

xc7: techmap: Remove localparam from generate blocks

---

xc/xc7/techmap/cells_sim.v

`CARRY4_VPR` is parametric, but also marked as a `blackbox`; this confuses ABC9 because you can't monomorphise blackboxes, and so it has no way of knowing if the timings it computes are accurate. I believe it is correct to instead mark it as `lib_whitebox` so that ABC9 can monomorphise it properly.

Mark CARRY4_VPR as lib_whitebox

---

xc/xc7/techmap/retarget.v

Per discussion in slack, fixing a typo in this arch definition. @Ravenslofty

Update retarget.v to fix TECHMAP_REPLACE typo

---

requirements.txt

Remove directly rapidyaml reference from requirements.

---

.github/kokoro/ql.sh
common/cmake/devices.cmake
common/cmake/install.cmake
quicklogic/common/cmake/quicklogic_install.cmake
quicklogic/common/cmake/quicklogic_qlf_arch.cmake
quicklogic/common/cmake/quicklogic_qlf_device.cmake
quicklogic/common/toolchain_wrappers/ql_symbiflow
quicklogic/common/toolchain_wrappers/symbiflow_repack
quicklogic/common/toolchain_wrappers/vpr_common
quicklogic/qlf_k4n8/CMakeLists.txt
quicklogic/qlf_k4n8/devices/umc22/CMakeLists.txt
quicklogic/qlf_k4n8/utils/CMakeLists.txt
quicklogic/qlf_k4n8/utils/repacker/README.md
quicklogic/qlf_k4n8/utils/repacker/arch_xml_utils.py
quicklogic/qlf_k4n8/utils/repacker/block_path.py
quicklogic/qlf_k4n8/utils/repacker/eblif_netlist.py
quicklogic/qlf_k4n8/utils/repacker/netlist_cleaning.py
quicklogic/qlf_k4n8/utils/repacker/packed_netlist.py
quicklogic/qlf_k4n8/utils/repacker/pb_rr_graph.py
quicklogic/qlf_k4n8/utils/repacker/pb_rr_graph_netlist.py
quicklogic/qlf_k4n8/utils/repacker/pb_rr_graph_router.py
quicklogic/qlf_k4n8/utils/repacker/pb_type.py
quicklogic/qlf_k4n8/utils/repacker/repack.py
quicklogic/qlf_k4n8/utils/repacker/tests/eblif_roundtrip/netlist.golden.eblif
quicklogic/qlf_k4n8/utils/repacker/tests/eblif_roundtrip/test_eblif_roundtrip.py
quicklogic/qlf_k4n8/utils/repacker/tests/identity.xsl
quicklogic/qlf_k4n8/utils/repacker/tests/packed_netlist_roundtrip/netlist.golden.net
quicklogic/qlf_k4n8/utils/repacker/tests/packed_netlist_roundtrip/test_netlist_roundtrip.py
quicklogic/qlf_k4n8/utils/repacker/tests/sort_netlist.xsl

The repacking is a step during which so called "operating cells" used by the VPR packer are converted into so called "phsyical cells" used by the physical device architecture. Both cell sets are defined within different models of relevant pb_types in the VPR architecture. The step involves revoking packing and routing of each cluster and then rebuilding it using physical cells only. The conversion is compliant with the `repack` step as deifined in the OpenFPGA project (https://openfpga.readthedocs.io/en/master/manual/openfpga_shell/openfpga_commands/fpga_bitstream_commands/#repack).
Repacking is added to the CMake flow through a new general mechanism of packed netlist patching. One may define an external utility run between VPR placement and VPR routing stages. See …

QuickLogic qlf_k4n8 repacker

---

quicklogic/common/cmake/quicklogic_qlf_arch.cmake
quicklogic/qlf_k4n8/utils/CMakeLists.txt
quicklogic/qlf_k4n8/utils/repacker/repack.py
quicklogic/qlf_k4n8/utils/repacker/tests/lut_padding/lut1.eblif
quicklogic/qlf_k4n8/utils/repacker/tests/lut_padding/lut1_0.golden.eblif
quicklogic/qlf_k4n8/utils/repacker/tests/lut_padding/lut1_0.net
quicklogic/qlf_k4n8/utils/repacker/tests/lut_padding/lut1_1.golden.eblif
quicklogic/qlf_k4n8/utils/repacker/tests/lut_padding/lut1_1.net
quicklogic/qlf_k4n8/utils/repacker/tests/lut_padding/lut1_2.golden.eblif
quicklogic/qlf_k4n8/utils/repacker/tests/lut_padding/lut1_2.net
quicklogic/qlf_k4n8/utils/repacker/tests/lut_padding/lut1_3.golden.eblif
quicklogic/qlf_k4n8/utils/repacker/tests/lut_padding/lut1_3.net
quicklogic/qlf_k4n8/utils/repacker/tests/lut_padding/test_lut_padding.py

This is based on top of #2137, and it will need a rebase after #2137 is merged.
The PR fixes an issue with the repacker around the LUT fasm outputs. It also adds a test to verify that the fix is working as expected.

QuickLogic: upstream repacker fixes

---

.gitmodules
environment.yml
quicklogic/common/toolchain_wrappers/conda_build_install_package.sh

This PR updates revisions of both mentioned packages which is required for up-to-date `qlf_k4n8` eFPGA support. The updated `qlf_fasm` provides support for default bitstream which is then mutated by a design FASM file.

QuickLogic: Update qlf-fasm and yosys-symbiflow-plugins

---

.github/kokoro/steps/hostsetup.sh
.github/kokoro/steps/rapidwright.sh
.github/kokoro/xc7-vendor.sh
.github/kokoro/xc7a200t-vendor.sh

Recent changes to rapidwright seem to require a newer version of jdk

kokoro: update to jdk 11

---

quicklogic/common/toolchain_wrappers/conda_build_install_package.sh
quicklogic/common/toolchain_wrappers/ql_symbiflow
quicklogic/qlf_k4n8/tests/design_flow/counter_16bit/counter_16bit.pcf

This PR updates the installed toolchain version to `2.0.1` and updates Conda environment setup script for it.
There is also a minor fix which adds a clock constraint to the `counter_16bit` design.

QuickLogic: Update installed toolchain version

---

docs/source/getting-started.rst

This PR expands `Getting Started` section with some useful information on environment setup and building example targets.

docs: expand "getting started" section

---

docs/source/getting-started.rst

This PR addresses https://github.com/SymbiFlow/symbiflow-docs/issues/368
It adds information on the OpenOCD programming tool and mentions the other ones that are also used in Symbiflow.
Signed-off-by: Paweł Czarnecki <pczarnecki@antmicro.com>

docs: add info on OpenOCD

---

environment.yml
quicklogic/pp3/techmap/cells_map.v

This PR updates the `yosys-symbiflow-plugins` conda package and renames ports of some QuickLogic PP3 cells to align with the change.

[PP3] Update Yosys plugins

---

environment.yml

This PR removes the `file:` prefix given before `requirements.txt` in `environment.yaml`. The prefix makes conda provide incorrect file path to `pip`.

Remove file: from environment.yaml

---

.github/workflows/update_conda_lock.yml
Makefile
conda_lock.yml
environment.yml

This PR adds a bot for creating and updating locks for Conda and Pip packages. It consists of a GitHub Actions workflow which handles `git` and creates a Pull Request and `update_conda_lock.py` script, which creates or updates locks.
Basically, it creates Conda environment based on `environment.yml` (which shouldn't be locked, but locked will work too) and creates locks based on Conda and Pip packages installed.
Currently the workflow added can only be run manually and that's how I tested it. It can be easily modified to work regularly on schedule of course. For now there are some simple constants used for PR title, user creating commit and commit title but these are easily configurable. For testing purposes I set them to be set as an input of the manual workflow.
To to use locks during …

Add bot locking and updating Conda and Pip packages

---

.github/workflows/update_conda_lock.yml

gha: add name and email for the conda lock updating bot

---

.github/kokoro/steps/hostsetup.sh

Fixes the issue appearing as;
```
========================================
Host adding PPAs
----------------------------------------
gpg: no valid OpenPGP data found.
[ID: 7946271] Build finished after 82 secs, exit value: 2
```
Which is actually an issue caused by the kitware.com SSL certificate not being understood by the ancient Ubuntu running on the kokoro host.
Info was discovered by @sdamghan at https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/1864

Fix SSL certificate issues with kitware.com causing Kokoro CI failures

---

docs/source/getting-started.rst

This PR introduces a new FPGA programming tool - OpenFPGALoader
It is addressing issue https://github.com/SymbiFlow/symbiflow-arch-defs/issues/2237
We are adding a note in the docs with a plan to add a full support for this tool in the future.
Signed-off-by: Paweł Czarnecki <pczarnecki@antmicro.com>

docs: Introduce OpenFPGALoader programming tool

---

.github/check-status/check-status.py

For some reason, the Kokoro status does not appear as `pending` anymore using the GH API to get a commit's status.
This could cause a potential update of the latest package even though a test fails after the package has been updated, as all the succeeding CI checks trigger the latest package update.
This PR ensures that all CI checks have passed, by adding a check to wait for the main CI (`Architecture Definitions`) to complete, before proceeding with the latest link update.

gh: check statuses: skip latest package update if main CI did not finish

---

xc/xc7/techmap/cells_map.v
xc/xc7/tests/mmcm/CMakeLists.txt
xc/xc7/tests/mmcm/README.md
xc/xc7/tests/mmcm/mmcm_none_basys3_bottom.v
xc/xc7/tests/mmcm/mmcme2_test.v

The Xilinx 7 Series Clocking Resources User Guide (UG 472) instructs users to NOT set a value for COMPENSATION since the Xilinx tools will choose one based on the design.  However, the guide offers no additional detail on how the Xilinx tools do that.  
As a result, standard user designs without a COMPENSATION parameter value are defaulting to ZHOLD (in the Symbiflow techmapper) which results in non-functional bitstreams. 
Testing has shown that setting the default COMPENSATION to INTERNAL or EXTERNAL generates functional bitstreams (by generating a bitstream with FASM feature Z_ZHOLD for the MMCM).
I note that the MMCM tests currently in the repo all set COMPENSATION to a specific value rather than leaving it at a default.  Thus, before this PR is ready for review the intention is to add …

Change MMCME2 advanced COMPENSATION parameter to have a default of INTERNAL

---

common/cmake/devices.cmake
conda_lock.yml
quicklogic/qlf_k4n8/tests/synth_flow/rgb2ycrcb/CMakeLists.txt
xc/xc7/techmap/cells_map.v
xc/xc7/yosys/synth.tcl

The conda lock update revealed a couple of issues with the most recent yosys.
This PR tries to fix these.
1. FD retargetting seems not to be working anymore. Now, the cell to retarget is add as a library module and it gets techmapped after synthesis
2. Yosys introduced `-r <topmodule>` option. This is now added when calling yosys.

Fixes due to yosys changes

---

xc/common/primitives/slicem/slicem.pb_type.xml

This fixes an issue for which the `BDI` input of the `ADI1MUX` was coming directly from the common slice's DI input, which is a connection that is not present in the Series7 slicem. Instead, the `BDI` input must come from the `BDI1MUX` output, as clearly seen in the device view:
The previous bug was causing conflicting FASM features on the BDI1MUX which was getting configured to use two inputs at the same time (namely, `BI` and `DI`).

xc: common: slicem: enforce correct intra-pb-type path for ADI1MUX input

---

docs/source/prjxray/partial-reconfig.rst
docs/source/prjxray/vtr-rrgraph.rst

This PR fixes some issues reported by Sphinx with regard to titles and code-blocks. BTW, spacing is homogenised.

docs: fix rst syntax issues (titles and code-blocks)

---

conda_lock.yml

This fixes failing ``surelog`` test due to missing ``builtin.sv``.
Signed-off-by: Kamil Rakoczy <krakoczy@antmicro.com>

Update surelog and symbiflow-yosys-plugins packages.

---

.readthedocs.yml
docs/Makefile

It seems that RTD is currently using Python 2.7 to build the docs. This is an attempt to use Python 3.

docs/Makefile: use sphinx-build to avoid Python 2.7

---

.readthedocs.yml
docs/conf.py
docs/development/structure.rst
docs/getting-started.rst

This PR is blocked by #2397.
As discussed in SymbiFlow/symbiflow-docs#521, this PR adds extensions ExtLinks and InterSphinx to the docs. The content is updated to use them.

docs: use extensions ExtLinks and InterSphinx

---

conda_lock.yml
quicklogic/qlf_k4n8/CMakeLists.txt

Since a PR has been merged to VPR which allows to control handling of unconnected ports when writing post-layout Verilog netlist additional control parameters have to be provided to maintain legacy behavior.

[k4n8] Add VPR options to mimic legacy behavior

---

xc/common/utils/prjxray_create_place_constraints.py
xc/xc7/tests/mmcm/CMakeLists.txt
xc/xc7/tests/mmcm/mmcm_dual.v

This PR relaxes the constraint that enforces a `PLL`/`MMCM` and its driving `IBUF` to be in the same CMT region. This is required in case when a single `IBUF` drives more than one `PLL`/`MMCM`.
The constraint is relaxed in a way that among all `PLL`/`MMCM` driven by an `IBUF` at least one of them is required to be in the same CMT region. Therefore the change should not affect placement quality of existing designs.

Fix issues with constraining multiple PLL/MMCM for xc7

---

docs/conf.py
docs/development/arch_notes.rst
docs/index.rst

Enhance docs with details on new tiles/primitives addition

---

xc/common/utils/prjxray_create_place_constraints.py

xc/common/utils: allow to have less or equal IDELAYE2 than IDELAYCTRL

---

.github/ci/install.sh
.github/workflows/ci.yml

Added package uploading to GCP but only from builds from the `main` branch.
Uploading has been tested by temporarily disabling the actual tests and enabling uploads from PRs which yielded in the test package: https://console.cloud.google.com/storage/browser/symbiflow-arch-defs/artifacts/prod/foss-fpga-tools/symbiflow-arch-defs/continuous/install/20220401-132741.
The actual package will be created and uploaded only upon merge.

GCP package uploading

---

.github/workflows/update_conda_lock.yml
requirements.txt

This reverts commit 9242920f0ae2837f4bad957b3afb359857a3d196.
There are some packages that use `setuptools-scm` to get the version of the package from either `git` or `metadata` (https://pypi.org/project/setuptools-scm/).

Revert "requirements: s/SymbiFlow/F4PGA/; do not require git"

---

.github/ci/install.sh

Packages are uploaded to GCS through `gsutil cp ${package} gs://${GCP_PATH}/${TIMESTAMP}/`. Unfortunately, the target is hidden in the logs:
https://github.com/SymbiFlow/f4pga-arch-defs/runs/6472094719?check_suite_focus=true#step:4:24660
```
Copying file://symbiflow-arch-defs-xc7a50t-arty-swbut-overlay_test-11aa9fd.tar.xz [Content-Type=application/x-tar]...
```
Therefore, users cannot guess the URL of the arch-def packages generated by some specific commit. They know the format, they know the hash, but they don't know the specific timestamp. This PR prints it.
Ref chipsalliance/f4pga-examples#292

ci: print packages' timestamp in job 'install'

---

.github/ci/install.sh
.github/workflows/Tests.yml

This PR is based on #2674.
Instead of uploading the packages to the GCS at the end of script `.github/ci/install.sh`, those 5-7 lines of code are written as an additional step in the CI workflow. This is to make it easier for users/contributors to find the packages uploaded by a CI run.

ci/install: upload packages in a separated step

---

.github/workflows/Automerge.yml

This pull request fixes the bug in CI where the `GCP_STORAGE_BUCKET` was missing and was causing the Install job to fail.
It's not possible to prove that this fix works by looking at the CI jobs executed by this pull request, so I prepared a [test branch](https://github.com/SymbiFlow/f4pga-arch-defs/commits/test-secrets) that demonstrates that after adding the secret inheritance policy, the secret is passed. I'll remove that branch if the fix works on main after this PR gets merged in.
I'm leaving some links to the documentation that describes using secrets and inputs in reusable workflows:
* https://docs.github.com/en/actions/using-workflows/reusing-workflows
* https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callsecrets

Inherit secrets in Tests.yml

---

environment.yml
requirements.txt

`python-fpga-interchange` requires v1.1.0:
https://github.com/chipsalliance/python-fpga-interchange/blob/27fc1db2a37f5e224396c50f0770ea0caef708d9/requirements.txt
so there's a conflict.
Also let's use Pip v21.1.3 instead of the latest; its output for the conflicts is almost instant and great:
https://github.com/antmicro/f4pga-arch-defs/runs/7114351446?check_suite_focus=true#step:3:736
compared to 3.5h it takes v21.2.2 to fail during conflict resolution:
https://github.com/SymbiFlow/f4pga-arch-defs/runs/7105019813?check_suite_focus=true#step:3:906

requirements: Loosen `pycapnp` version constraint to fix the conflict

---

.github/workflows/Automerge.yml

The `GCS` job is failing, reportedly due to _coordinator <-> worker_ connectivity issues. Together with @kamilrakoczy we have investigated this and we discovered that it is actually not the OpenSSH process that is failing and returning the 255 exit but the underlying command (to be precise, it is `apt-key` specifically; see `apt-key` [source code](https://git.launchpad.net/ubuntu/+source/apt/tree/cmdline/apt-key.in?h=applied/ubuntu/bionic&id=93d330ad1a7475675fda8c575f7097d82898eb67#n679)).
The following message is produced by the custom runner:
> This error indicates issues with communication with the worker instance.
In most cases it is fair to assume that the 255 exit code is coming from OpenSSH. Anecdotally, programs don't usually use such high exit code and the OpenSSH seems to have …

ci/GCS: install gnupg2

---

xc/xc7/techmap/cells_map.v

This fixes a situation where yosys outputs parameters with more bits than required, causing a FASM writing failure, as the expected width of the parameter is not respected.
E.g. the `DOA_REG` parameter has only one bit and, if an integer is used to define the parameter in verilog, the `DOA_REG` parameter will have a total of 32 bits, generating a failure when writing FASM from VPR.

xc: xc7: fix parameters width for RAMB

---

xilinx/xc7/tests/install_test/Makefile

Required because of https://github.com/chipsalliance/f4pga/pull/614.
Ref: #1682.

xilinx/xc7/tests/install_test/Makefile: use '--' to separate additional VPR options

---

xilinx/common/primitives/slicem/slicem.pb_type.xml
xilinx/xc7/tests/dram/CMakeLists.txt

This fixes a situation for which the `ADI1MUX` in `SLICEMs`, when in `DRAM64` mode, could have an input directly connected to the `BI` `SLICEM` input port, therefore bypassing the `BDI1MUX` routing bel, causing a potential conflict in case the `BDI1MUX` was connected to something else than `BI`
This would fix https://github.com/chipsalliance/fpga-tool-perf/issues/444

xc: xc7: fix AD1MUX inputs to avoid conflicting bits

---

xilinx/xc7/techmap/cells_map.v

Ibex synthesis in [yosys-systemverilog][ysv-ibex-makefile] using F4PGA toolchain & arch-defs and latest Yosys fails with the following error:
```
${YSV_REPO}/UHDM-integration-tests/env/symbiflow/share/f4pga/techmaps/xc7_vpr/techmap/cells_map.v:0: ERROR: Can't find object for defparam `SIM_DEVICE`!
Traceback (most recent call last):
File "${YSV_REPO}/UHDM-integration-tests/env/conda/envs/surelog_xc7/bin/symbiflow_synth", line 8, in <module>
sys.exit(synth())
File "${YSV_REPO}/UHDM-integration-tests/env/conda/envs/surelog_xc7/lib/python3.10/site-packages/f4pga/wrappers/sh/__init__.py", line 569, in synth
p_run_sh_script(ROOT / SH_SUBDIR / "synth.f4pga.sh", env=env)
File "${YSV_REPO}/UHDM-integration-tests/env/conda/envs/surelog_xc7/lib/python3.10/site-packages/f4pga/wrappers/sh/__init__.py", …
```

Add (no-op) `SIM_DEVICE` parameter to xc7 `BUFGCE`.
