common/make/sim.mk, common/make/w.mk
=> Fixing makefiles.

tests/const.eblif, tests/wire.eblif
Signed-off-by: David Shah <davey1576@gmail.com>
=> Add some super simple examples

common/make/arch.mk, common/make/prjxray-clb.mk, common/make/prjxray-int.mk, common/make/sim.mk, common/make/w.mk
=> common: realpath is a Makefile builtin.

artix7/primitives/slicel/carry4/carry4_split/carry4_wmux/Makefile.mux, artix7/primitives/slicel/carry4/carry4_split/carry4_wmux/sim.v, artix7/primitives/slicel/muxes/f7amux/Makefile.mux, artix7/primitives/slicel/muxes/f7bmux/Makefile.mux, artix7/primitives/slicel/muxes/f8mux/Makefile.mux, artix7/primitives/slicel/routing/affmux/Makefile.mux, artix7/primitives/slicel/routing/aoutmux/Makefile.mux, artix7/primitives/slicel/routing/bffmux/Makefile.mux, artix7/primitives/slicel/routing/boutmux/Makefile.mux, artix7/primitives/slicel/routing/cffmux/Makefile.mux, artix7/primitives/slicel/routing/coutmux/Makefile.mux, artix7/primitives/slicel/routing/dffmux/Makefile.mux, artix7/primitives/slicel/routing/doutmux/Makefile.mux, artix7/primitives/slicel/routing/precyinit_mux/Makefile.mux, artix7/primitives/slicel/routing/w5ffmux/Makefile.mux, artix7/primitives/slicel/routing/wcy0/Makefile.mux, common/make/gen.mk, common/make/mux.mk, utils/lib/argparse_extra.py, utils/lib/asserts.py, utils/mux_gen.py
* Refactoring how `mux_gen.py` Makefile works.
* Fixing `gen.mk`
=> Two makefile fixes

.github/autolabeler.yml
=> Adding autolabeler configuration.

.travis.yml, make/env.mk, make/inc/env.mk, make/xml.mk
=> env: Adding xsltproc to environment.

.travis.yml, make/inc/common.mk
=> Using bash as shell in Makefile

.gitignore, Makefile, make/env.mk, make/inc/env.mk, utils/Makefile, utils/conftest.py, utils/lib/deps.py, utils/pytest.ini
* Uses pytest as the runner.
* Runs the tests on travis.
* Fixes the currently broken tests.
=> Adding running of python tests

.travis.yml, make/env.mk, make/gen.mk, make/inc/env.mk, make/sim.mk, make/third_party.mk
Means people have one less dependency to install themselves.
=> Use nodejs from conda

artix7/primitives/slicem/slicem.model.merged.xml, artix7/primitives/slicem/slicem.pb_type.merged.xml, utils/mux_gen.py, vpr/muxes/logic/mux2/mux2.sim.v
A few one-off cleanup items I ran into while testing other things
=> Fix MUX generation and remove generated SLICEM merged.xml files

README.md
Minor things I hit when going through the getting started section of README.
=> Add more detail to getting started section of README.

artix7/blocks/clbll_l-int_l/pb_type.xml, artix7/blocks/int_r-clbll_r/pb_type.xml, artix7/devices/xc7a50t-roi-virt/arch.xml, ice40/devices/tile-routing-virt/arch.xml, ice40/devices/tile-routing-virt/tiles/pio-lr/pio-lr.fc.xml, ice40/devices/tile-routing-virt/tiles/pio-tb/pio-tb.fc.xml, ice40/devices/tile-routing-virt/tiles/plb/plb.pb_type.xml, ice40/devices/tile-routing-virt/tiles/ramb/ramb.pb_type.xml, ice40/devices/tile-routing-virt/tiles/ramt/ramt.pb_type.xml, ice40/devices/top-routing-virt/arch.xml, ice40/devices/top-routing-virt/tiles/pio/pio.pb_types.xml, ice40/devices/top-routing-virt/tiles/plb/plb.pb_type.xml, ice40/devices/top-routing-virt/tiles/ramb/ramb.pb_type.xml, ice40/devices/top-routing-virt/tiles/ramt/ramt.pb_type.xml, testarch/devices/routing/unidir-s4.xml, tests/Makefile
* Using a simpler dummy fabric to make generating rr_graphs faster.
* Cleaning up XML which is now enforced.
=> ice40: Fabric fixes

utils/print_graph.py, utils/reparse_graph.py, utils/testarch_graph.py
Mark a few executable scripts executable and add shebang
Signed-off-by: John McMaster <johndmcmaster@gmail.com>
=> Scripts executable

utils/lib/rr_graph/graph.py, utils/print_graph.py
Fixing print_graph (and fixing performance improvements) which was broken by my changes in #115.
=> rr_graph: Fixing print_graph tool

utils/lib/rr_graph/graph.py, utils/print_graph.py
Only allow valid edge types to be added to the routing graph. Also adds a lot of tests to prove things work.
=> rr_graph: Adding more sanity checking.

ice40/utils/ice40_patch_routing_from_icebox.py, utils/lib/collections_extra.py, utils/lib/rr_graph/graph.py, utils/print_graph.py
=> rr_graph: Add port names+index to the pretty print when available.

utils/lib/rr_graph/graph.py
Per
https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/319
Signed-off-by: John McMaster <johndmcmaster@gmail.com>
=> rr_graph: remove pin index

utils/check_graph.py
Signed-off-by: Ben Reynwar <ben@reynwar.net>
=> utils: Add utility to check that all sources can route to all sinks.

.travis/script.sh
It takes a long time to render everything.
=> travis: Disable `make render` for now.

ice40/devices/top-routing-virt/tiles/ram/ram.pb_type.xml, ice40/utils/ice40_import_routing_from_icebox.py, tests/ice40/blink/example.v, tests/ice40/blink/example_tb.v, tests/ice40/iceram/Makefile, tests/ice40/iceram/iceblink40-lp1k.pcf, tests/ice40/iceram/iceram.v, tests/ice40/iceram/iceram_tb.v, tests/ice40/iceram/icestick.pcf, tests/make/arch/ice40.mk, tests/make/test-common.mk
* Add iceram test for reading from initialized RAM
* Fix offsets
* Generate testbench and testbinch results to show expected behavior
Tested: flashed icestick with iceram test (#138)
=> ice40: Add support for iceram

artix7/make/tests.mk, ice40/make/tests.mk, make/tests.mk, testarch/make/tests.mk
io.place files weren't being generated because PLACE_TOOL wasn't being set due to order of variables being set
=> make/test: fix PLACE_TOOL and comment update

ice40/devices/top-routing-virt/arch.xml, ice40/make/tests.mk, ice40/utils/ice40_list_layout_in_icebox.py
Fixes tinyfpga-b2 configuration.
=> Add support for lp8k part

common/xml/README.md, common/xml/fpga_architecture.xsd, common/xml/packed_netlist.xsd, common/xml/routing_resource.xsd
This could be used for validation and as a potential base for autogenerating import/export code detailed in https://github.com/SymbiFlow/ideas/issues/4
=> Add preliminary schemas for VPR XML files.

make/inc/common.mk
=> make: Check submodules are initialized.

ice40/tests/murax/CMakeLists.txt, make/file_targets.cmake, utils/deps_verilog.py, utils/deps_xml.py
Add missing add_file_target for murax system RAM symbols.
=> Add $readmemb directive to verilog scanner.

utils/deps_verilog.py, utils/deps_xml.py, utils/lib/deps.py, utils/listfiles.py
Rebasing some simplification I had started a while ago.
=> utils: simplify and clean up formatting of dependency generation

CMakeLists.txt, make/devices.cmake
Signed-off-by: Jeffrey Elms <elmsfu@freshred.net>
=> Add cmake commands and use genhlc to generate HLC as separate step

make/devices.cmake
Signed-off-by: Keith Rothman <537074+litghost@users.noreply.github.com>
=> Fix echo targets.

README.md
Signed-off-by: Brian Swetland <swetland@frotz.net>
=> README: fix links to third_party projects

ice40/CMakeLists.txt, ice40/yosys/synth.tcl, make/devices.cmake, xc7/archs/artix7/CMakeLists.txt, xc7/archs/zynq7/CMakeLists.txt, xc7/yosys/synth.tcl
=> Convert yosys scripts to TCL.

soc_tests/murax/README.md, soc_tests/murax/basys3.pcf, soc_tests/murax/basys3_toplevel.v, xc7/tests/common/CMakeLists.txt, xc7/tests/common/basys3.pcf, xc7/tests/common/error_output_logic.v
This does require another prjxray-db update which is in progress now.
=> Working Murax on 7-series parts.

README.md, utils/lib/rr_graph/graph.py, utils/lib/rr_graph/tests/test_graph.py
As part of #339, I started to write tests to verify existing behavior. During tests, I found some additional instructions to add to the README, and a fix to be made to the graph.py souce.
Let me know if the current changes look good, and if so I'll continue work on the issue.
=> Adds tests for graph.py

tests/CMakeLists.txt
=> tests: Fix FULL_BOARDS for artix7.

README.md
=> docs: Small improvements to the README.

utils/lib/rr_graph/graph2.py, utils/lib/rr_graph_xml/graph2.py, xc7/utils/prjxray_routing_import.py
Before:
Elapsed (wall clock) time (h:mm:ss or m:ss): 4:42.76
Maximum resident set size (kbytes): 28813976
After:
Elapsed (wall clock) time (h:mm:ss or m:ss): 4:13.61
Maximum resident set size (kbytes): 3633376
=> Switch to incremental XML writing to cut down on peak memory usage.

utils/lib/rr_graph/graph2.py, utils/lib/rr_graph_xml/graph2.py, xc7/utils/prjxray_routing_import.py
Before: ~4 minutes, max memory usage 3.5 GB
After: ~2 minutes, max memory usage 2.5 GB
Working on #292
=> Optimize routing import on 7-series.

xc7/tests/buttons/buttons_zybo.v, xc7/tests/buttons/zybo.pcf
this PR updates the button test for zybo, so it corresponds to roi in harness project
=> zybo: Updated buttons test to support latest ROI

Makefile, xc7/make/project_xray.cmake
* cherry-pick @mkurc-ant's Python dependency fix.
* Adding top level `make clean` target.
=> Two minor fixes.

Makefile
=> Fix make call in file.

xc7/make/project_xray.cmake
=> Fix indenting issue.

.gitmodules, CMakeLists.txt, common/xml/fpga_architecture.xsd, ice40/CMakeLists.txt, ice40/boards.cmake, ice40/cells/lutff/lutff.pb_type.xml, ice40/cells/plb/plb.pb_type.xml, ice40/devices/top-routing-virt/tiles/pio/pio.pb_type.xml, ice40/primitives/sb_ff/sb_ff.pb_type.xml, ice40/primitives/sb_ram/sb_ram.pb_type.xml, ice40/tests/iceram/iceram.v, ice40/utils/fasm_icebox/README.md, ice40/utils/fasm_icebox/asc2fasm.py, ice40/utils/fasm_icebox/fasm2asc.py, ice40/utils/fasm_icebox/fasm_icebox_utils.py, ice40/utils/fasm_icebox/ice40_feature.py, ice40/utils/fasm_icebox/tests/test_fasm_icebox_utils.py, ice40/utils/ice40_import_layout_from_icebox.py, ice40/utils/ice40_import_routing_from_icebox.py, ice40/yosys/synth.tcl, make/env.cmake
- Add fasm metadata
- Add tools for converting between FASM and ASC
Fixes #468
=> FASM for ice40

xc7/utils/prjxray_create_edges.py
Hard code them as output pins.
=> Ignore INOUT pins for now.

make/env.cmake
=> Use conda `--force-reinstall` instead of deprecated `--force`

utils/mux_gen.py
mux_gen.py is satisfying pep8 #13
=> Make mux_gen.py satisfy pep8

xc7/fasm2bels/clb_models.py, xc7/fasm2bels/make_routes.py, xc7/fasm2bels/verilog_modeling.py
- Give unique names to DRAMs within a SLICEM.
- Output const0 and const1 fixed routing.
- Handle case where part of the CARRY4 needs to be removed to prevent
net conflict.
Signed-off-by: Keith Rothman <537074+litghost@users.noreply.github.com>
=> Fix bugs found in 7-series FASM to verilog.

CMakeLists.txt, ice40/devices/top-routing-virt/arch.xml, make/devices.cmake, testarch/CMakeLists.txt, testarch/devices/routing/unidir-s4.xml, testarch/utils/testarch_graph.py, utils/lib/rr_graph/tracks.py
Requires VPR with
https://github.com/verilog-to-routing/vtr-verilog-to-routing/commit/08b8a0f51cbd553edf5b91a081e2d7ddf06d5681
=> Implement global constant routing network in testarch.

xc7/tests/CMakeLists.txt, xc7/tests/ff_sr_ce/CMakeLists.txt, xc7/tests/ff_sr_ce/ff_ce_sr.v
This is the beginning of an equivilance test for FF SR and CE control
signals.
=> Add FF SR/CE signal test.

Makefile
=> Forward make targets to build/ directory.

make/devices.cmake, utils/compare_usage.py, utils/gather_usage.py, utils/lib/parse_usage.py, utils/report_block_usage.py, utils/usage.py
These tools were created to provide a way to answer whether https://github.com/SymbiFlow/symbiflow-arch-defs/pull/576 and features like round robin packing were adversely affecting packing quality.
=> Add usage comparision tools.

xc7/fasm2bels/clb_models.py
=> Fix typos in clb_models.py affecting the RAM32X1D LUT mode

xc7/fasm2bels/fasm2bels.py
=> fasm2bels: hotfix after graph2.py changes

utils/CMakeLists.txt
=> utils: add intervaltree to test dependencies

xc7/primitives/slicem/dram.md, xc7/primitives/slicem/modes.md, xc7/primitives/slicem/shift.md
* LUT-RAM configurations + descriptions.
* Shift register configurations.
=> xc7: Adding notes for SLICEM.

utils/vlog/tests/dsp_out_registered/golden.pb_type.xml, utils/vlog/tests/v2x_tests.cmake, utils/vlog/vlog_to_pbtype.py
=> v2x: update comment in cmake and added xml header to golden pb_type

utils/vlog/vlog_to_pbtype.py, utils/vlog/yosys/json.py
=> utils: v2x: handle implicit cells

common/cmake/devices.cmake, common/cmake/env.cmake, common/cmake/xml.cmake
* Small cleanup of some cmake files.
* Fix a weird bug where conda was being downloaded many times.
=> Bunch of small cmake fixes

xc7/techmap/cells_map.v, xc7/tests/dram/CMakeLists.txt, xc7/tests/dram/dram_1_64m.pcf, xc7/tests/dram/dram_1_64m.v, xc7/tests/dram_shifter/CMakeLists.txt, xc7/tests/dram_shifter/dram_shifter_64m.v, xc7/tests/dram_test/CMakeLists.txt, xc7/tests/dram_test/dram_test_64m.v
=> Add RAM64M

xc7/tests/bram_shifter/bram_shifter.v
Signed-off-by: Dusty DeWeese <dustin.deweese@gmail.com>
=> Force bram_shifter to actually use block RAM

tests/9-soc/picosoc/README.md
=> picosoc: updated README

xc7/primitives/common_slice/common_slice.pb_type.xml
=> xc7: Fixing mux name.

utils/check_ptc.py, utils/lib/connection_database.py, utils/lib/connection_database.sql, utils/lib/rr_graph/graph2.py, utils/lib/rr_graph/tests/test_graph2.py, utils/lib/rr_graph_xml/graph2.py, xc7/utils/prjxray_arch_import.py, xc7/utils/prjxray_assign_tile_pin_direction.py, xc7/utils/prjxray_create_edges.py, xc7/utils/prjxray_form_channels.py, xc7/utils/prjxray_routing_import.py
This is the initial 7-series routing import, which currently just writes 0 delays for all routing, but will use timing information from prjxray-db once present.
=> Initial xc7 route timing import.

xc7/fasm2bels/clb_models.py, xc7/fasm2bels/verilog_modeling.py, xc7/utils/vivado_create_runme.py
This only handles cell's with single outputs, but that covers all FF's
and some LUT's.
=> Add some cell annotations based on net names.

common/cmake/devices.cmake
=> Correct dependency chain for IO placement file.

utils/deps_verilog.py, utils/lib/argparse_extra.py, utils/lib/collections_extra.py, utils/lib/deps.py, utils/lib/mux.py, utils/lib/rr_graph/__main__.py, utils/lib/rr_graph/channel.py, utils/lib/rr_graph/graph.py, utils/lib/rr_graph/tracks.py, utils/vpr_pbtype_arch_wrapper.py, utils/vpr_pbtype_to_eblif.py
=> utils: Fail on doctest.testmod failure.

CMakeLists.txt, utils/CMakeLists.txt
Fixes https://github.com/SymbiFlow/symbiflow-arch-defs/issues/767
=> cmake: Fix dependencies for Python targets.

common/xml/fpga_architecture.xsd
This change needs validation, I've never done xsd before.
Fixes #774
=> xml: Adding tiles schema.

tox.ini, utils/lib/rr_graph/channel.py, utils/lib/rr_graph/graph2.py
- Change namedtuples to classes with docstrings
- Address Flake8 for these files
=> Add docstrings to graph2 channel

utils/rr_graph_walk/README.md, utils/rr_graph_walk/rr_graph_walk.py
This tool allows to traverse the VPR routing graph. It allows to verify if there is a possible route between two VPR nodes. It also allows to list all possible routes when starting from a given node id. The search is exhaustive.
=> A tool for traversing VPR routing graph

CMakeLists.txt, xc7/make/arch_define.cmake
This PR also updates VTR conda revision
=> Add strict checks option

CMakeLists.txt
Incorporates https://github.com/SymbiFlow/vtr-verilog-to-routing/pull/70
=> Update to latest VPR.

README.md
Signed-off-by: Qinziyue Xu <xqzy1014@gmail.com>
=> Add resource requirement for running examples

.github/travis/common.sh, .github/travis/script.sh
Have travis build in parallel and handle rebuilding to display error messages clearly as recommended in #815
=> travis: wrap make in function to handle parallel building

CMakeLists.txt
=> Update VTR version

xc7/fasm2bels/clb_models.py, xc7/fasm2bels/make_routes.py, xc7/fasm2bels/verilog_modeling.py
- Handle single element list creation in TCL.
- Ensure that LUT-RAM's are inserted D -> A (which is required by
Vivado).
=> Fix some bugs fasm2bels bugs.

tests/9-scalable_proc/CMakeLists.txt, tests/9-soc/murax/CMakeLists.txt, tests/9-soc/murax/basys3.pcf, tests/9-soc/murax/basys3.sdc, tests/9-soc/murax/basys3_toplevel.v, tests/9-soc/picosoc/CMakeLists.txt, tests/9-soc/picosoc/basys3_demo.v
Also make murax compatible with fasm2bels.
=> Add constraints to scalable_proc, murax, picosoc.

.github/kokoro/continuous-docs.cfg, .github/kokoro/continuous-ice40.cfg, .github/kokoro/continuous-testarch.cfg, .github/kokoro/continuous-tests.cfg, .github/kokoro/continuous-xc7.cfg, .github/kokoro/ice40.sh, .github/kokoro/presubmit-docs.cfg, .github/kokoro/presubmit-ice40.cfg, .github/kokoro/presubmit-testarch.cfg, .github/kokoro/presubmit-tests.cfg, .github/kokoro/presubmit-xc7.cfg, .github/kokoro/xc7.sh, CMakeLists.txt, common/cmake/env.cmake, utils/print_qor.py
This adds a simple QoR summary tool and binds Kokoro to gather this summary and the other VPR outputs.
=> Add QoR tool

CMakeLists.txt, ice40/icestorm.cmake, utils/lib/rr_graph/graph.py
- Also pin libusb version, looks like a new version of libusb snuck in (1.0.20 -> 1.0.22) that caused an additional udev dep.
=> Fixes fragile doctests that were depending on hash table order.

utils/print_qor.py
- Outputs git commit and branch to tag QoR results with where they came
from.
- Fix reversed critical path and Fmax fields.
=> Update QoR printing tool.

CMakeLists.txt, xc7/yosys/synth.tcl
This may result in an SRL16, which will cause a failure.
=> [XC7] Attempt to enable SRL synthesis.

tests/9-soc/picosoc/CMakeLists.txt, xc7/archs/artix7/devices/CMakeLists.txt, xc7/archs/zynq7/devices/CMakeLists.txt, xc7/fasm2bels/bram_models.py, xc7/make/arch_define.cmake, xc7/make/device_define.cmake, xc7/utils/prjxray_create_ioplace.py, xc7/utils/prjxray_synth_tiles_to_pinmap_csv.py
- Adds picosoc vivado target
- Fixes bug in BRAM model for write widths other than 18.
=> Add output of iostandard_defs.json from PCF format.

common/cmake/devices.cmake, utils/check_cache.py, utils/update_cache.py
=> Avoid cache rebuild

common/cmake/devices.cmake, tests/9-soc/murax/CMakeLists.txt, tests/9-soc/picosoc/CMakeLists.txt, xc7/make/vivado.cmake, xc7/techmap/unmap.v, xc7/tests/dram_test/CMakeLists.txt, xc7/utils/prjxray_pcf_to_xdc.py
This enables direct post-synthesis Vivado comparisions with VPR easily.
=> Add Vivado P&R targets.

.github/kokoro/package_results.sh
Collect ninja runtime data for diagnosing build times.
=> Add ninja runtime data to collected data.

xc7/fasm2bels/bram_models.py, xc7/fasm2bels/make_routes.py, xc7/fasm2bels/verilog_modeling.py, xc7/techmap/cells_map.v, xc7/tests/bram_test/CMakeLists.txt
=> Correct RAMB36E1 write enables and add fasm2v support.

docs/requirements.txt, docs/source/conf.py
This PR changes the theme used in Sphinx from Symbiflow to Material Design.
=> Change theme to Sphinx Material Design

utils/lib/connection_database.sql, xc7/utils/prjxray_assign_tile_pin_direction.py, xc7/utils/prjxray_create_edges.py, xc7/utils/prjxray_form_channels.py
The vast majority of pips that connect to site pins connect within the
same tile, however this is not true of some of the pips in the IOB/IOI
tiles.
=> Handle site pins that connect to pips not in the same tile.

utils/lib/rr_graph/channel2.py, utils/lib/rr_graph/tests/test_channel2.py
New algorithm is significantly faster, and avoids creating Interval
objects.
Part of prjxray_create_edge scaling work to reach full 50T in reasonable time.
=> Refactor channel2 track packing algorithm.

xc7/utils/prjxray_create_edges.py
This is part of the refactoring to improve create edges time.
- Remove usage of multiprocess now that channel creation is fast
- Remove alive tracks set, and let sqlite filter (via index).
- Refactor edge creation into function.
=> Initial refactor of create edges.

xc7/tests/srl/common/srl_init_tester.v, xc7/tests/srl/common/srl_shift_tester.v
Should fix problem in https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1040
=> Fix uninitialized regs in the SRL test suite design

CMakeLists.txt, utils/update_arch_tiles.py, xc7/archs/artix7/tiles/slicem/CMakeLists.txt, xc7/make/project_xray.cmake, xc7/utils/prjxray_arch_import.py, xc7/utils/prjxray_physical_tile_import.py
This PR adds the direct pin mappings to the architecture files.
=> equivalent tiles: modified import scripts to add direct pin mappings

CMakeLists.txt
=> Pin libxml2 to version with fix.

xc7/make/device_define.cmake
Testing to see that picosoc and murax still behave after this.
=> Relax router effort when creating the place delay matrix.

CMakeLists.txt
=> Update VtR to latest version

xc7/utils/prjxray_edge_library.py
Some INPINFEED's have shorted legs, which result in a graph node with two
outbound edges, but one is simply back to the previous graph node of the
same track.  This results in walk_and_mark_segment stopping earlier than
it should have.
As a practical result, this means that some connection boxes are
mislabeled (example as BYP_L instead of BYP_ALT).  After this change,
all BYP_L's become BYP_ALT, and all FAN_L's become FAN_ALT as expected.
=> Fix walking through INPINFEED's with shorts.

utils/update_tools/update_tools.py
This PR solves the issue reported in [this comment](https://github.com/SymbiFlow/symbiflow-arch-defs/issues/1068#issuecomment-542857524)
=> update_tool: encapsulate suprocess in try except

CMakeLists.txt, requirements.txt, utils/convert_connection_box_to_mat.py, utils/lib/connection_box_tools.py, utils/plot_connection_box.py, utils/print_connection_map_lookahead.py
- Adds tool for plotting connection box data
- Adds tool for convert connection box data in `.mat` file
- Refactors common logic into library.
=> Refactor connection box tools

utils/simple_router_analysis.py
This PR solves a code-style bug that leads to a Travis-CI failure.
=> utils: fix code-style error

xc7/utils/prjxray_define_segments.py, xc7/utils/prjxray_edge_library.py
@acomodi I'm hoisting out this change, because I suspect it will improve routing performance in general.
=> Update segments with GCLK and PLL in/out pin feeds.

xc7/utils/prjxray_edge_library.py
Example failure: https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1168#issuecomment-557650671
=> Attempt to fix pip ordering to match canonical ordering.

CMakeLists.txt, xc7/techmap/cells_map.v
=> Update to latest upstream yosys.

README.md
=> readme: add instruction to correctly compile conda

xc7/fasm2bels/bram_models.py, xc7/fasm2bels/fasm2bels.py, xc7/fasm2bels/hclk_ioi3_models.py, xc7/fasm2bels/verilog_modeling.py, xc7/make/arch_define.cmake, xc7/tests/soc/litex/mini/CMakeLists.txt, xc7/tests/soc/litex/mini/minilitex.xdc, xc7/tests/soc/litex/mini/minilitex_arty.v, xc7/utils/prjxray_create_place_constraints.py
- Enable mini LiteX diff fasm test and add explicit BUFG LOC.
Fixes #1183
=> Enable LOC constraints of tiles with capacity.

xc7/utils/prjxray_routing_import.py
This PR solves the issue for which the pips related to the IOI_SING tiles are incorrect, as they should refer to the correct half of a full IOI tile.
With these changes, the IOI_SING pip features get modified according to the correct IOI half they belong to.
Example of fasm feature modification:
```
RIOI3_SING_X43Y49.IOI_OCLKM_0.IOI_SING_LEAF_GCLK5 --> RIOI3_SING_X43Y49.IOI_OCLKM_1.IOI_LEAF_GCLK5 
```
=> xc7: added RL_IOI_SING tile pips correct fasm_feature

xc7/make/vivado.cmake, xc7/utils/vivado_create_runme.py
This PR adds a change to output reports after routing is successful during fasm2bels.
=> output reports after fasm2bels

xc7/archs/artix7/CMakeLists.txt, xc7/archs/zynq7/CMakeLists.txt, xc7/make/arch_define.cmake, xc7/make/device_define.cmake, xc7/make/project_xray.cmake, xc7/make/vivado.cmake
This will be used to enable support for artix7 200T parts.
=> Split CMake arch target from prjxray arch folder.

xc7/utils/prjxray_edge_library.py
This workaround is required because of the workaround present in prjxray
around LV pip data.
Needs prjxray-db after 84b1457b885861fee221c5c6255d41cfb962ffc0
=> Add workaround for LV wire R/C values.

CMakeLists.txt, common/cmake/devices.cmake, common/cmake/env.cmake, utils/lib/rr_graph_capnp/graph2.py, xc7/fasm2bels/fasm2bels.py, xc7/make/arch_define.cmake, xc7/utils/prjxray_routing_import.py
- Converts fasm2bels to use capnp for faster rr graph reading.
- Converts xc7 routing import to use capnp for faster rr graph reading
and writing.
=> Working initial capnp based rr graph patcher.

utils/lib/connection_database.sql, xc/common/utils/prjxray_arch_import.py, xc/common/utils/prjxray_form_channels.py
This PR adds the possibility to skip the physical tile import in the DB whenever the tiles contain prohibited sites.
This requires first https://github.com/SymbiFlow/prjxray/pull/1278
=> xc7: skip prohibited sites during physical tiles import

.github/travis/script.sh, .travis.yml, CMakeLists.txt, common/cmake/devices.cmake, common/cmake/env.cmake, common/cmake/file_targets.cmake, common/cmake/timings.cmake, ice40/devices/top-routing-virt/CMakeLists.txt, ice40/icestorm.cmake, utils/CMakeLists.txt, xc/common/CMakeLists.txt, xc/common/cmake/arch_define.cmake, xc/common/cmake/project_ray.cmake, xc/common/utils/CMakeLists.txt, xc/xc7/CMakeLists.txt
This PR holds all necessary changes to the common part of the CMake build system required for Quicklogic FPGAs support.
=> Improvements to the CMake system for Quicklogic EOS S3/PP3E support

CMakeLists.txt
Bumped VtR conda package to master+wip @0ece2d2 with the placement fix.
=> Bump VPR (placement fix)

xc/common/utils/prjxray_create_place_constraints.py
This PR fixes the placement constraint generation script. It also adds ability to lock placement of IDELAYCTRL.
=> Bugfixes for prjxray_create_place_constraints.py 

xc/common/utils/prjxray_form_channels.py
This PR fixes the vpr grid map from vpr locations to canonical locations.
=> channels: fix vpr grid map generation

xc/common/cmake/arch_define.cmake
=> vpr: suppress RR graph tool comment warning

README.md
Fixes #1450.
Signed-off-by: Tim 'mithro' Ansell <tansell@google.com>
=> docs: Adding build badges to README file.

xc/common/utils/vivado_create_runme.py
=> diff_fasm: speedup generation of vendor tools bitstreams

xc/xc7/fasm2bels/bram_models.py
This PR should fix https://github.com/SymbiFlow/symbiflow-arch-defs/issues/1400
=> brams: fix VCC fan bounce issue

CMakeLists.txt, xc/xc7/boards.cmake, xc/xc7/tests/common/CMakeLists.txt, xc/xc7/tests/common/zybo_z7.pcf, xc/xc7/tests/counter/CMakeLists.txt, xc/xc7/tests/counter/counter_zybo_z7.v
This is in preperation for a Zynq example on symbiflow-examples which I will be adding later.
=> Add support for Digilent Zybo Z7 (-20) FPGA board.

xc/common/primitives/slicem/slicem.pb_type.xml
Trying out suggested fix for #1625
=> Make sure DLUT.RAM is emitted if using LUT-RAMs.

xc/common/cmake/device_define.cmake
=> Use dijkstra for place delay expansion calculation.

xc/xc7/toolchain_wrappers/symbiflow_generate_constraints, xc/xc7/toolchain_wrappers/symbiflow_place
=> toolchain: remove necessity of PCF file

docs/source/getting-started.rst
Addressing: https://github.com/SymbiFlow/symbiflow-docs/issues/367
=> Review getting started, point to symbiflow-examples

.github/workflows/checkstatus.yml
GH actions will be used to get the latest successfull symbiflow install package.
The GH workflow works only if the yml configuration file is added to the master branch, where it will get to be effective on any status change for commits within the master branch.
Moreover, currently the GCS upload of the generated link is not present at the moment.
=> Initial GH actions activation

.github/workflows/checkstatus.yml
Signed-off-by: Karol Gugala <kgugala@antmicro.com>
=> CI: fix latest package URL getter tool name

README.md
Signed-off-by: Michael Gielda <mgielda@antmicro.com>
=> Review README, add note about symbiflow-examples

.github/check-status/action.yml
=> check-status: remove variable from yml description of the gh action

.github/kokoro/install-200t.sh, .github/kokoro/install.sh
This PR also enables the 200T device installation within the other device's installation, so to have all of the devices in one package only.
=> Add environment configuration to install tarball

.github/kokoro/continuous-ql.cfg, .github/kokoro/kokoro-cfg.py, .github/kokoro/presubmit-ql.cfg, .github/kokoro/ql.sh
This PR contains a basic configuration for the QuickLogic CI, as suggested in https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1758#issuecomment-723222892.
=> Add QuickLogic CI configuration

utils/print_qor.py
This PR improves the `print_qor` script in the following ways:
- sorts tests, so that they are more easily readable
- takes only the last two directories in the path (to avoid common paths to be added for each test
- collects only the relevant run-times in the P&R flow, excluding the overhead.
=> print_qor: sorted tests by name and remove prefix

xc/xc7/techmap/retarget.v, xc/xc7/yosys/synth.tcl
=> yosys: add retargeting step for FD primitives

environment.yml, requirements.txt
Fixes #1826 , superceeds #1827.
=> Fix pip requirements

.github/kokoro/xc7-vendor.sh, .github/kokoro/xc7a200t-vendor.sh
Vivado can hang if not started and terminated once.
=> Run URAY_VIVADO once before running in parallel.

.github/kokoro/common.sh, .github/kokoro/steps/movehome.sh
=> Move HOME to /tmpfs.

.github/kokoro/continuous-docs.cfg, .github/kokoro/continuous-ice40.cfg, .github/kokoro/continuous-ql.cfg, .github/kokoro/continuous-testarch.cfg, .github/kokoro/continuous-tests.cfg, .github/kokoro/continuous-xc7-vendor.cfg, .github/kokoro/continuous-xc7.cfg, .github/kokoro/continuous-xc7a200t-vendor.cfg, .github/kokoro/continuous-xc7a200t.cfg, .github/kokoro/kokoro-cfg.py, .github/kokoro/package_results.sh, .github/kokoro/presubmit-docs.cfg, .github/kokoro/presubmit-ice40.cfg, .github/kokoro/presubmit-ql.cfg, .github/kokoro/presubmit-testarch.cfg, .github/kokoro/presubmit-tests.cfg, .github/kokoro/presubmit-xc7-vendor.cfg, .github/kokoro/presubmit-xc7.cfg, .github/kokoro/presubmit-xc7a200t-vendor.cfg, .github/kokoro/presubmit-xc7a200t.cfg, .github/kokoro/steps/hostsetup.sh, .github/kokoro/xc7.sh
Attempting to get a bead on segfaults seen in https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1674
=> Make sure core dumps are recorded

xc/xc7/toolchain_wrappers/symbiflow_synth, xc/xc7/yosys/synth.tcl
=> xc7: yosys: allow custom top module instead of using only auto-top

environment.yml, xc/common/cmake/project_ray.cmake, xc/common/utils/prjxray_get_fabric.py
Handles the new location of the fabric data inside the database. A new tool is needed to get the fabric for a part number.
This PR needs the latest version of prjxray and prjxray-db. I'm not sure how the process of upgrading these packages is.
=> Handle different location of fabric data

.github/workflows/ci.yml
=> gh-actions: ci: use ubuntu-18.04

environment.yml, quicklogic/common/cmake/quicklogic_install.cmake, quicklogic/common/toolchain_wrappers/conda_build_install_package.sh, quicklogic/common/toolchain_wrappers/ql_symbiflow, quicklogic/common/toolchain_wrappers/symbiflow_generate_constraints, quicklogic/qlf_k4n8/tests/CMakeLists.txt, quicklogic/qlf_k4n8/tests/counter_16bit/CMakeLists.txt, quicklogic/qlf_k4n8/tests/counter_16bit/counter_16bit.sdc, quicklogic/qlf_k4n8/tests/counter_16bit/counter_16bit.v, quicklogic/qlf_k4n8/tests/counter_16bit/counter_16bit_tb.v, quicklogic/qlf_k4n8/yosys/synth.tcl
This PR has the following changes:
1) wrapper script changes to support external csv from user
2) sample counter example
3) Refer the symbiflow-yosys package in environment.yml
4) yosys plugin re-named to qlf-k4n8.so
=> Adding support for the quicklogic toolchain

common/cmake/devices.cmake
This PR solves the issue for which, if no external RR graph was provided and the rr_graph patching was required (this is true for xc7 devices), the real RR graph was never generated, and the patched one was directly used. This resulted in the installation package to lack the real RR graph, with a consequent failure of the install tests.
The fix in this PR enables the generation of the real RR graph in case the patching is required, otherwise, the externally provided rr graph (used only by the QL devices) is used as final RR graph target.
=> cmake: fix rr graph targets to generate the real rr graph

.github/kokoro/steps/rapidwright.sh, xc/common/cmake/arch_define.cmake
Signed-off-by: Jan Kowalewski <jkowalewski@antmicro.com>
=> Use Xilinx/RapidWright with pinned tag

common/cmake/devices.cmake, quicklogic/common/toolchain_wrappers/ql_symbiflow, quicklogic/common/toolchain_wrappers/symbiflow_analysis, quicklogic/common/toolchain_wrappers/vpr_common, quicklogic/qlf_k4n8/techmap/cells_sim.v, utils/vpr_fixup_post_synth.py
This is based on top of https://github.com/SymbiFlow/symbiflow-arch-defs/pull/2137, and it will need a rebase after #2137 is merged.
The PR adds fixes to allow a correct post-P&R analysis
=> QuickLogic: upstream post synth analysis fixes

environment.yml, quicklogic/common/cmake/quicklogic_install.cmake, quicklogic/common/toolchain_wrappers/ql_symbiflow, quicklogic/common/toolchain_wrappers/symbiflow_generate_libfile, quicklogic/common/toolchain_wrappers/symbiflow_place, quicklogic/qlf_k4n8/utils/create_lib.py, quicklogic/qlf_k4n8/utils/gather_lib_data.py
This PR is based on top of https://github.com/SymbiFlow/symbiflow-arch-defs/pull/2142.
It adds the feature to generate liberty files to the toolchain, using the data in `qlfpga-symbiflow-plugins` repository.
=> QuickLogic: upstream liberty data generation

common/cmake/v2x.cmake, utils/concatenate_v_sources.py, utils/lib/rr_graph_xml/graph2.py, utils/split_inouts.py, utils/update_arch_tiles.py, utils/update_arch_timings.py
This PR incorporates all changes needed for common CMake scripts as well as for common utility Python scripts required for QuickLogic EOS-S3 eFPGA support.
=> [EOS-S3] Changes to common CMake and Python scripts

.gitmodules
This PR adds Git submodules needed for QuickLogic EOS-S3 eFPGA support
=> [EOS-S3] Sumbodules

README.md
=> readme: add quicklogic

.github/workflows/update_conda_lock.yml
=> ci: bump conda lock action version

requirements.txt
=> quicklogic: pin quicklogic_fasm python library

requirements.txt
=> requirements: fix typo in QL fasm

.github/workflows/update_conda_lock.yml
=> gh: conda lock: reduce frequency to once a week

.github/workflows/update_conda_lock.yml
=> gh-actions: update conda lock version and issue PR with deploy key

.github/workflows/update_conda_lock.yml, conda_lock.yml, environment.yml, quicklogic/qlf_k4n8/tests/design_flow/CMakeLists.txt
This fixes the error described here: https://github.com/SymbiFlow/symbiflow-arch-defs/pull/2323#issuecomment-974268385.
This also adds the `merge-if-green` label, to auto merge all successful conda bot update PRs
=> Fix conda packaging issue

.github/workflows/update_conda_lock.yml
=> gh actions: update conda bot: fix set output call

.github/check-status/Dockerfile
This PR should fix https://github.com/SymbiFlow/symbiflow-arch-defs/issues/2363
=> ci: fix check tests docker image build

environment.yml, xc/xc7/tests/install_test/CMakeLists.txt, xc/xc7/tests/install_test/Makefile, xc/xc7/toolchain_wrappers/symbiflow_synth
This PR extends ``symbiflow_synth`` wrapper giving option to read input files using Surelog/UHDM with uhdm-plugin.
Signed-off-by: Kamil Rakoczy <krakoczy@antmicro.com>
=> Add support for reading files using uhdm-plugin

README.md
=> readme: s/SymbiFlow/F4PGA/

.github/workflows/update_conda_lock.yml
=> ci: conda bot: run every day

xc/xc7/tests/soc/litex/generate.py, xc/xc7/tests/soc/litex/mini/CMakeLists.txt
This PR bumps LiteX submodules and includes `generate.py` fixups to work with the latest LiteX.
PR can be merged after HW tests using generated bitstreams from litex examples are proven to work
=> LiteX submodules update

xc/xc7/techmap/cells_map.v
=> xc: xc7: techmap: add missing inputs to RAMB36E1

.github/workflows/update_conda_lock.yml, requirements.txt
=> requirements: re-add changes to point to chipsalliance packages

.github/scripts/install.sh, .github/scripts/ql.sh
Cosmetic change to unfiy the naming convention with `F4PGA_INSTALL_DIR`
=> Rename F4PGA_ENV_* to F4PGA_*_DIR

.github/scripts/install_ql.sh, .github/scripts/install_xc7.sh, .github/scripts/ql.sh, .github/workflows/Tests.yml, common/cmake/install.cmake, quicklogic/common/cmake/quicklogic_install.cmake, xc/common/cmake/install.cmake
This PR moves QuickLogic installed toolchain tests to a separate job in order to fix package generation for QL. It also fixes some inconsistencies in locations of utility scripts. This PR is Cross-dependent with: https://github.com/chipsalliance/f4pga/pull/587
=> Fix QuickLogic install job

.github/workflows/Tests.yml, packaging/eos-s3_environment.yml, packaging/eos-s3_requirements.txt, packaging/xc7_requirements.txt
=> packaging: bump environment

docs/conf.py
Updated the link in the docs to the f4pga-arch-defs repo.
=> updated link to f4pga-arch-defs repo

docs/development/getting-started.rst
Fixed broken link to f4pga-arch-defs
=> Fixed broken link to f4pga-arch-defs

docs/bitdoc/prjxray/partial-reconfig.rst
Fixed broken links due to xc/ moving to xilinx/xc/.
=> fixed broken links

docs/bitdoc/prjxray/partial-reconfig.rst
=> fixed links
